# Generated by Django 2.2.4 on 2019-12-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentDisciplineLog',
        ),
    ]
