# Generated by Django 2.2.4 on 2019-12-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_auto_20191225_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchangelog',
            name='sent_data',
            field=models.TextField(blank=True, default='', verbose_name='Отправленные данные '),
        ),
    ]
