# Generated by Django 2.2.11 on 2020-07-23 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emc', '0002_auto_20200722_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='emc',
            name='name',
            field=models.CharField(default='name_emc', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emc',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emcs', to='organizations.Discipline'),
        ),
    ]
