# Generated by Django 2.2.4 on 2020-04-30 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.RemoveField(
            model_name='subtype',
            name='code',
        ),
        migrations.RemoveField(
            model_name='type',
            name='code',
        ),
        migrations.AddField(
            model_name='subapplication',
            name='completed_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выполнения'),
        ),
        migrations.AlterField(
            model_name='status',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code of status'),
        ),
    ]
