# Generated by Django 2.2.4 on 2020-04-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_auto_20200421_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='send',
            field=models.BooleanField(default=False, verbose_name='Is send to 1C'),
        ),
    ]
