# Generated by Django 2.2.4 on 2020-04-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subapplication',
            name='virtual',
        ),
        migrations.AddField(
            model_name='subapplication',
            name='is_paper',
            field=models.BooleanField(default=True, verbose_name='Бумажный вариант'),
        ),
    ]
