# Generated by Django 2.2.4 on 2020-04-24 13:52

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20200423_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='application',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.AddField(
            model_name='subapplication',
            name='responsible',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Ответственный специалист'),
        ),
        migrations.AddField(
            model_name='subapplication',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applications.Status', verbose_name='Status'),
        ),
        # migrations.AlterField(
        #     model_name='subapplication',
        #     name='lang',
        #     field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=5), default=list, size=3, verbose_name='Язык'),
        # ),
        migrations.AlterField(
            model_name='subtype',
            name='example',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applications.Example', verbose_name='Document example'),
        ),
    ]
