# Generated by Django 2.2.4 on 2020-06-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_auto_20200520_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtype',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
