# Generated by Django 2.2.4 on 2020-07-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20200630_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='subapplication',
            name='uuid1c',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
