# Generated by Django 2.2.4 on 2020-04-24 14:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20200424_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subapplication',
            name='lang',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=list, size=3, verbose_name='Языки'),
        ),
    ]
