# Generated by Django 2.2.4 on 2020-04-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_auto_20200424_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='subapplication',
            name='comment',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Комментарий к статусу'),
        ),
    ]
