# Generated by Django 2.2.4 on 2020-07-30 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0039_changelog_editor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal_users', '0071_role_is_columnist'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('is_important', models.BooleanField(default=False, verbose_name='Важная новость?')),
                ('pub_date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('addressees', models.ManyToManyField(blank=True, to='portal_users.Profile', verbose_name='Адресаты')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='Автор новости')),
                ('files', models.ManyToManyField(blank=True, to='common.File', verbose_name='Прикрепленные файлы')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
