# Generated by Django 2.2.4 on 2020-08-04 14:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0134_auto_20200729_0829'),
        ('auth', '0011_update_proxy_permissions'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cathedras',
            field=models.ManyToManyField(blank=True, to='organizations.Cathedra', verbose_name='Кафедры'),
        ),
        migrations.AddField(
            model_name='news',
            name='courses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(), blank=True, null=True, size=None, verbose_name='Курсы'),
        ),
        migrations.AddField(
            model_name='news',
            name='education_programs',
            field=models.ManyToManyField(blank=True, to='organizations.EducationProgram', verbose_name='Обр. программы'),
        ),
        migrations.AddField(
            model_name='news',
            name='faculties',
            field=models.ManyToManyField(blank=True, to='organizations.Faculty', verbose_name='Факультеты'),
        ),
        migrations.AddField(
            model_name='news',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='Группы'),
        ),
        migrations.AddField(
            model_name='news',
            name='prep_levels',
            field=models.ManyToManyField(blank=True, to='organizations.PreparationLevel', verbose_name='Уровни образования'),
        ),
        migrations.AddField(
            model_name='news',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None, verbose_name='Типы ролей'),
        ),
    ]
