# Generated by Django 2.2.4 on 2019-08-29 05:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_studyform'),
        ('portal_users', '0004_auto_20190828_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationToken',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('token', models.UUIDField(default=uuid.uuid4, verbose_name='Токен')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='organizations.Organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Токен для Организации',
                'verbose_name_plural': 'Токены для Организации',
            },
        ),
    ]
