# Generated by Django 2.2.4 on 2019-08-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0006_auto_20190829_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='iin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ИИН'),
        ),
    ]
