# Generated by Django 2.2.4 on 2019-08-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0008_auto_20190829_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'verbose_name': 'Увлечение', 'verbose_name_plural': 'Увлечения'},
        ),
    ]
