# Generated by Django 2.2.4 on 2019-09-04 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0013_auto_20190903_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
    ]
