# Generated by Django 2.2.4 on 2019-09-05 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0015_auto_20190904_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gender',
            old_name='name_kz',
            new_name='name_kk',
        ),
        migrations.RenameField(
            model_name='maritalstatus',
            old_name='name_kz',
            new_name='name_kk',
        ),
    ]
