# Generated by Django 2.2.4 on 2019-09-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0016_auto_20190905_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Отчество'),
        ),
    ]
