# Generated by Django 2.2.4 on 2019-09-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0018_auto_20190912_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementtype',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='achievementtype',
            name='name_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='achievementtype',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='level',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='level',
            name='name_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='level',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
    ]
