# Generated by Django 2.2.4 on 2019-09-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0019_auto_20190912_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_id',
            field=models.IntegerField(help_text='Из 1С', null=True, verbose_name='ID студента'),
        ),
    ]
