# Generated by Django 2.2.4 on 2019-09-13 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0020_profile_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nationality',
        ),
    ]
