# Generated by Django 2.2.4 on 2019-09-13 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_citizenship_nationality'),
        ('portal_users', '0021_auto_20190913_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='citizenship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Citizenship', verbose_name='Гражданство'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Nationality', verbose_name='Национальность'),
        ),
    ]
