# Generated by Django 2.2.4 on 2019-09-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0022_auto_20190913_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='entry_date',
        ),
    ]
