# Generated by Django 2.2.4 on 2019-10-08 08:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0048_loadtype2_number'),
        ('portal_users', '0023_remove_profile_entry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('academic_degree', models.CharField(default='', max_length=100, verbose_name='Ученая степень')),
                ('academic_rank', models.CharField(default='', max_length=100, verbose_name='Ученое звание')),
                ('work_experience', models.CharField(max_length=100, verbose_name='Стаж работы в ВУЗ')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Профиль')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeacherPosition',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('is_main', models.BooleanField(default=False, verbose_name='Основная должность')),
                ('cathedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Cathedra')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_users.Position', verbose_name='Должность')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_users.Teacher', verbose_name='Учитель')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
