# Generated by Django 2.2.4 on 2019-10-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0024_position_teacher_teacherposition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Преподаватель', 'verbose_name_plural': 'Преподаватели'},
        ),
        migrations.AlterModelOptions(
            name='teacherposition',
            options={'verbose_name': 'Должность преподавателя', 'verbose_name_plural': 'Должности преподавателей'},
        ),
    ]
