# Generated by Django 2.2.4 on 2019-10-08 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0025_auto_20191008_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='position',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='position',
            name='name_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='position',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_experience_month',
            field=models.CharField(default='', max_length=100, verbose_name='Стаж работы в ВУЗ (Месяц)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_experience_year',
            field=models.CharField(default='', max_length=100, verbose_name='Стаж работы в ВУЗ (Год)'),
        ),
    ]
