# Generated by Django 2.2.4 on 2019-10-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0026_auto_20191008_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='academic_degree',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ученая степень'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='academic_rank',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ученое звание'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_experience_month',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Стаж работы в ВУЗ (Месяц)'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='work_experience_year',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Стаж работы в ВУЗ (Год)'),
        ),
    ]
