# Generated by Django 2.2.4 on 2019-10-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0027_auto_20191008_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Cотрудник', 'verbose_name_plural': 'Cотрудники'},
        ),
        migrations.AlterModelOptions(
            name='teacherposition',
            options={'verbose_name': 'Должность сотрудника', 'verbose_name_plural': 'Должности сотрудников'},
        ),
    ]
