# Generated by Django 2.2.4 on 2019-10-08 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0028_auto_20191008_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherposition',
            name='cathedra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Cathedra', verbose_name='Подразделение'),
        ),
        migrations.AlterField(
            model_name='teacherposition',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_users.Teacher', verbose_name='Сотрудник'),
        ),
    ]
