# Generated by Django 2.2.4 on 2019-12-01 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0032_auto_20191129_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherposition',
            name='teacher',
        ),
        migrations.AddField(
            model_name='teacherposition',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Профиль'),
        ),
    ]
