# Generated by Django 2.2.4 on 2019-12-11 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal_users', '0034_auto_20191203_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='login_sent',
            field=models.BooleanField(default=False, verbose_name='Логин отправлен'),
        ),
        migrations.CreateModel(
            name='UserCredential',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пароль пользователя',
                'verbose_name_plural': 'Пароли пользователей',
            },
        ),
    ]
