# Generated by Django 2.2.4 on 2019-12-11 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0037_auto_20191211_1220'),
    ]

    operations = [
    ]
