# Generated by Django 2.2.4 on 2019-12-11 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0038_auto_20191211_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='profile_new',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='portal_users.Profile', verbose_name='Пользователь'),
        ),
    ]
