# Generated by Django 2.2.4 on 2019-12-11 06:24

from django.db import migrations


def move_to_one2one_profile(apps, schema_editor):
    Role = apps.get_model('portal_users', 'Role')

    for role in Role.objects.all():
        role.profile_new = role.profile_old
        role.save()


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0039_role_profile_new'),
    ]

    operations = [
        migrations.RunPython(move_to_one2one_profile),
    ]
