# Generated by Django 2.2.4 on 2019-12-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0067_auto_20191211_1431'),
        ('portal_users', '0042_auto_20191211_1256'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherposition',
            unique_together={('profile', 'position', 'cathedra')},
        ),
    ]
