# Generated by Django 2.2.4 on 2019-12-11 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0067_auto_20191211_1431'),
        ('portal_users', '0044_teacherposition_study_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacherposition',
            unique_together={('profile', 'position', 'cathedra', 'study_year')},
        ),
    ]
