# Generated by Django 2.2.4 on 2019-12-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0045_auto_20191211_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephone',
            name='value',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
    ]
