# Generated by Django 2.2.4 on 2019-12-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0046_auto_20191214_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementtype',
            name='name',
            field=models.CharField(max_length=800, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='name_en',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='name_kk',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='achievementtype',
            name='name_ru',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(max_length=800, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name_en',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name_kk',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gender',
            name='name_ru',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='interest',
            name='name',
            field=models.CharField(max_length=800, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=800, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name_en',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name_kk',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name_ru',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='name',
            field=models.CharField(max_length=800, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='name_en',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='name_kk',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='maritalstatus',
            name='name_ru',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='phonetype',
            name='name',
            field=models.CharField(max_length=800, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='phonetype',
            name='name_en',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='phonetype',
            name='name_kk',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='phonetype',
            name='name_ru',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=800, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name_en',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name_kk',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name_ru',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studentstatus',
            name='name',
            field=models.CharField(max_length=800, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studentstatus',
            name='name_en',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studentstatus',
            name='name_kk',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studentstatus',
            name='name_ru',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
    ]
