# Generated by Django 2.2.4 on 2019-12-18 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0048_auto_20191218_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_changed',
            field=models.BooleanField(default=False, verbose_name='Сменил пароль'),
        ),
    ]
