# Generated by Django 2.2.4 on 2020-01-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0049_profile_password_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='password_changed',
            field=models.NullBooleanField(default=False, verbose_name='Сменил пароль'),
        ),
    ]
