# Generated by Django 2.2.4 on 2020-01-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0050_auto_20200104_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpassword',
            name='username',
            field=models.CharField(default='', max_length=150, verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='resetpassword',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
    ]
