# Generated by Django 2.2.4 on 2020-01-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0052_role_is_selection_committer'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='achievementtype',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='gender',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='interest',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='level',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='maritalstatus',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='organizationtoken',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='phonetype',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='position',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='profilephone',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='resetpassword',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='role',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='studentstatus',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='teacherposition',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='usercredential',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='usernamerule',
            name='sort',
            field=models.IntegerField(default=500),
        ),
    ]
