# Generated by Django 2.2.4 on 2020-02-10 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0053_auto_20200128_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephone',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='portal_users.Profile', verbose_name='Профиль'),
        ),
    ]
