# Generated by Django 2.2.4 on 2020-03-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0054_auto_20200210_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_applicant',
            field=models.BooleanField(default=False, verbose_name='Абитуриент'),
        ),
    ]
