# Generated by Django 2.2.4 on 2020-02-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0054_auto_20200221_0524'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interest',
            unique_together={('profile', 'name')},
        ),
    ]
