# Generated by Django 2.2.4 on 2020-03-12 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0055_role_is_applicant'),
        ('portal_users', '0055_auto_20200225_1056'),
    ]

    operations = [
    ]
