# Generated by Django 2.2.4 on 2020-04-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('portal_users', '0056_merge_20200312_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notify_me_from_email',
            field=models.NullBooleanField(default=True, verbose_name='Оповещать по почте'),
        ),
    ]
