# Generated by Django 2.2.4 on 2020-03-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0056_merge_20200312_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_mod',
            field=models.BooleanField(default=False, verbose_name='Модератор'),
        ),
    ]
