# Generated by Django 2.2.4 on 2020-04-10 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0057_profile_notify_me_from_email'),
        ('portal_users', '0058_auto_20200403_1152'),
    ]

    operations = [
    ]
