# Generated by Django 2.2.4 on 2020-04-24 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0060_infoshowpermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infoshowpermission',
            options={'verbose_name': 'Разрешение для отображения инфо пользователя', 'verbose_name_plural': 'Разрешения для отображения инфо пользователя'},
        ),
    ]
