# Generated by Django 2.2.4 on 2020-04-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0061_auto_20200424_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoshowpermission',
            name='identity_documents',
            field=models.BooleanField(default=False, verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='infoshowpermission',
            name='iin',
            field=models.BooleanField(default=False, verbose_name='ИИН'),
        ),
    ]
