# Generated by Django 2.2.4 on 2020-04-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0062_auto_20200427_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoshowpermission',
            old_name='education',
            new_name='educations',
        ),
    ]
