# Generated by Django 2.2.4 on 2020-05-18 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0063_auto_20200427_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_selection_committer',
        ),
    ]
