# Generated by Django 2.2.4 on 2020-06-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0065_auto_20200521_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_mod_can_edit',
            field=models.BooleanField(default=False, verbose_name='Права модератора на редактирование анкет'),
        ),
    ]
