# Generated by Django 2.2.4 on 2020-07-22 05:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0067_auto_20200630_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleNames',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('name', models.CharField(max_length=800, verbose_name='Название')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Католог наименования роли',
                'verbose_name_plural': 'Каталог наименования ролей',
            },
        ),
        migrations.CreateModel(
            name='RoleNamesRelated',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_name', to='portal_users.Profile', verbose_name='Профиль')),
                ('role_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_users.RoleNames', verbose_name='Имя роли')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
