# Generated by Django 2.2.4 on 2020-07-22 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0068_rolenames_rolenamesrelated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolenamesrelated',
            options={'verbose_name': 'Отношение роли к профилю', 'verbose_name_plural': 'Отношение ролей к профилям'},
        ),
    ]
