# Generated by Django 2.2.4 on 2020-07-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0069_auto_20200722_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilephone',
            name='modified_for_1c',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
