# Generated by Django 2.2.4 on 2019-08-28 08:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cron_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtask',
            name='id',
        ),
        migrations.AddField(
            model_name='emailtask',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор'),
        ),
    ]
