# Generated by Django 2.2.4 on 2019-08-29 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cron_app', '0003_resetpasswordurlsendtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialsEmailTask',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=False, verbose_name='Успешно')),
                ('to', models.EmailField(max_length=254, verbose_name='Email')),
                ('username', models.CharField(max_length=50, verbose_name='Логин')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
