# Generated by Django 2.2.4 on 2019-09-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron_app', '0005_notifyadvisortask'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpasswordurlsendtask',
            name='lang_code',
            field=models.CharField(default='ru', max_length=10, verbose_name='Код языка'),
        ),
    ]
