# Generated by Django 2.2.4 on 2019-10-15 07:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0049_studentdiscipline_study_year'),
        ('cron_app', '0006_resetpasswordurlsendtask_lang_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorRejectedBidTask',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=False, verbose_name='Успешно')),
                ('comment', models.CharField(max_length=500, verbose_name='Комментарий')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.StudyPlan', verbose_name='Учебный план')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
