# Generated by Django 2.2.4 on 2019-12-05 09:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0019_studentperformancelog'),
        ('cron_app', '0008_studperformancechangedtask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlNotifyTask',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=False, verbose_name='Успешно')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Lesson', verbose_name='Занятие')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
