# Generated by Django 2.2.4 on 2019-12-26 11:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0031_electronicjournal_study_year'),
        ('cron_app', '0009_controlnotifytask'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCloseJournalTask',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=False, verbose_name='Успешно')),
                ('date_time', models.DateTimeField(verbose_name='Дата время блокировки')),
                ('journals', models.ManyToManyField(to='schedules.ElectronicJournal', verbose_name='Журналы')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
