# Generated by Django 2.2.4 on 2020-01-08 08:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0050_auto_20200104_1424'),
        ('cron_app', '0010_planclosejournaltask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelTask',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('is_success', models.BooleanField(default=False, verbose_name='Успешно')),
                ('doc_type', models.IntegerField(choices=[(1, 'Результат регистрации'), (2, 'Статистика регистрации '), (3, 'Список незарегистрированных')], verbose_name='Тип документа')),
                ('token', models.UUIDField(verbose_name='Токен')),
                ('fields', models.TextField(verbose_name='Поля')),
                ('file', models.FileField(null=True, upload_to='', verbose_name='Файл')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Ексель файлы',
                'verbose_name_plural': 'Ексель файлов',
            },
        ),
    ]
