# Generated by Django 2.2.4 on 2020-01-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron_app', '0012_auto_20200108_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceltask',
            name='doc_type',
            field=models.IntegerField(choices=[(1, 'Результат регистрации'), (2, 'Статистика регистрации '), (3, 'Список незарегистрированных'), (4, 'Заявки на ИУПЫ обуч'), (5, 'ИУПЫ обуч')], verbose_name='Тип документа'),
        ),
    ]
