# Generated by Django 2.2.4 on 2020-01-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron_app', '0013_auto_20200110_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorrejectedbidtask',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='controlnotifytask',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='credentialsemailtask',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='emailtask',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='exceltask',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='notifyadvisortask',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='planclosejournaltask',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='resetpasswordurlsendtask',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='studperformancechangedtask',
            name='sort',
            field=models.IntegerField(default=500),
        ),
    ]
