# Generated by Django 2.2.4 on 2020-03-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron_app', '0014_auto_20200128_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceltask',
            name='ordering',
            field=models.CharField(default='-uid', max_length=200),
        ),
    ]
