# Generated by Django 2.2.4 on 2020-07-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron_app', '0015_exceltask_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtask',
            name='message',
            field=models.TextField(null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='emailtask',
            name='subject',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
