# Generated by Django 2.2.4 on 2020-03-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cron_app', '0015_exceltask_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceltask',
            name='ordering',
            field=models.CharField(default='-uid', max_length=1000),
        ),
    ]
