# Generated by Django 2.2.4 on 2019-09-04 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identitydocument',
            name='user',
        ),
    ]
