# Generated by Django 2.2.4 on 2019-09-04 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0015_auto_20190904_1432'),
        ('common', '0002_remove_identitydocument_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydocument',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identity_documents', to='portal_users.Profile', verbose_name='Пользователь'),
        ),
    ]
