# Generated by Django 2.2.4 on 2019-09-11 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0031_auto_20190910_1552'),
        ('common', '0004_courseacadperiodpermission_registrationperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseacadperiodpermission',
            name='registration_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_acad_periods', to='common.RegistrationPeriod', verbose_name='Период регистрации'),
        ),
        migrations.AlterUniqueTogether(
            name='courseacadperiodpermission',
            unique_together={('course', 'acad_period')},
        ),
    ]
