# Generated by Django 2.2.4 on 2019-09-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20190911_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydocument',
            name='issued_by',
            field=models.CharField(default='', max_length=100, verbose_name='Кем выдан'),
            preserve_default=False,
        ),
    ]
