# Generated by Django 2.2.4 on 2019-09-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20190913_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydocument',
            name='given_date',
            field=models.DateField(null=True, verbose_name='Дата выдачи'),
        ),
    ]
