# Generated by Django 2.2.4 on 2019-10-04 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0044_auto_20191003_1116'),
        ('common', '0009_citizenship_nationality'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseacadperiodpermission',
            unique_together={('course', 'acad_period', 'registration_period')},
        ),
    ]
