# Generated by Django 2.2.4 on 2019-10-08 05:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20191004_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCoeff',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('start_year', models.PositiveIntegerField(verbose_name='Год начала')),
                ('coeff', models.PositiveIntegerField(verbose_name='Коэффициент')),
            ],
            options={
                'verbose_name': 'Коэффициент кредита',
                'verbose_name_plural': 'Коэффициенты кредитов',
            },
        ),
    ]
