# Generated by Django 2.2.4 on 2019-12-10 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_registrationperiod_study_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitydocument',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.DocumentType', verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='given_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.GovernmentAgency', verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='identitydocument',
            name='validity_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок действия'),
        ),
    ]
