# Generated by Django 2.2.4 on 2019-12-10 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20191210_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydocument',
            name='issued_by_str',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Кем выдан (строка)'),
        ),
    ]
