# Generated by Django 2.2.4 on 2019-12-11 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0042_auto_20191211_1256'),
        ('common', '0014_identitydocument_issued_by_str'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='identitydocument',
            unique_together={('profile', 'document_type')},
        ),
    ]
