# Generated by Django 2.2.4 on 2019-12-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_auto_20191211_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizenship',
            name='name',
            field=models.CharField(max_length=800, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='citizenship',
            name='name_en',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='citizenship',
            name='name_kk',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='citizenship',
            name='name_ru',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=800, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name_en',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name_kk',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name_ru',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='governmentagency',
            name='name',
            field=models.CharField(max_length=800, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='governmentagency',
            name='name_en',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='governmentagency',
            name='name_kk',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='governmentagency',
            name='name_ru',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='name',
            field=models.CharField(max_length=800, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='name_en',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='name_kk',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='name_ru',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='registrationperiod',
            name='name',
            field=models.CharField(max_length=800, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='registrationperiod',
            name='name_en',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='registrationperiod',
            name='name_kk',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='registrationperiod',
            name='name_ru',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
    ]
