# Generated by Django 2.2.4 on 2019-12-27 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0049_profile_password_changed'),
        ('common', '0018_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='author',
        ),
        migrations.AddField(
            model_name='log',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_actions', to='portal_users.Profile', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='log',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
    ]
