# Generated by Django 2.2.4 on 2020-01-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0019_auto_20191227_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenship',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='courseacadperiodpermission',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='creditcoeff',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='governmentagency',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='identitydocument',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='log',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='nationality',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='registrationperiod',
            name='sort',
            field=models.IntegerField(default=500),
        ),
    ]
