# Generated by Django 2.2.4 on 2020-01-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0021_merge_20200128_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Номер'),
        ),
        migrations.AddField(
            model_name='course',
            name='sort',
            field=models.IntegerField(default=500),
        ),
    ]
