# Generated by Django 2.2.4 on 2020-04-08 11:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0015_auto_20200408_1656'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('portal_users', '0058_auto_20200403_1152'),
        ('common', '0023_auto_20200403_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('object_id', models.TextField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='portal_users.Profile')),
                ('files', models.ManyToManyField(blank=True, to='applicant.DocScan')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
