# Generated by Django 2.2.4 on 2020-05-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_changelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitydocument',
            name='number',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Номер'),
        ),
    ]
