# Generated by Django 2.2.4 on 2020-05-20 12:15

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_auto_20200519_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Имя файла')),
                ('path', models.FileField(upload_to='upload', verbose_name='Путь к файлу')),
                ('extension', models.CharField(blank=True, max_length=20, null=True, verbose_name='Расширение файла')),
                ('size', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20971520)], verbose_name='Размер файла')),
                ('content_type', models.CharField(blank=True, max_length=500, null=True, verbose_name='Тип контента')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('name', models.CharField(max_length=800, verbose_name='Название')),
                ('code', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('files', models.ManyToManyField(related_name='document', to='common.File', verbose_name='Файлы')),
            ],
            options={
                'verbose_name': 'Документы',
                'verbose_name_plural': 'Документы',
            },
        ),
    ]
