# Generated by Django 2.2.4 on 2020-05-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_auto_20200521_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='new_value',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Новое значение'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='old_value',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Старое значение'),
        ),
    ]
