# Generated by Django 2.2.4 on 2020-06-11 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_auto_20200521_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='types', to='common.DocumentTypeGroup', verbose_name='Группа типов'),
        ),
    ]
