# Generated by Django 2.2.4 on 2020-07-02 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_auto_20200630_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionConfig',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('bg_image', models.FileField(upload_to='upload', verbose_name='Задний фон')),
            ],
            options={
                'verbose_name': 'Настройки образовательного учреждения',
                'verbose_name_plural': 'Настройки образовательных учреждений',
            },
        ),
    ]
