# Generated by Django 2.2.4 on 2020-07-08 09:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_institutionconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('type', models.CharField(blank=True, editable=False, max_length=255, null=True, unique=True, verbose_name='Тип шаблона')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('template', models.TextField(blank=True, null=True, verbose_name='Шаблон письма')),
                ('is_dynamic', models.BooleanField(default=True, verbose_name='Шаблон динамический?')),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='email_templates', to='common.InstitutionConfig', verbose_name='Настройка ОУ')),
            ],
            options={
                'verbose_name': 'Шаблон письма',
                'verbose_name_plural': 'Шаблоны писем',
                'unique_together': {('config', 'type')},
            },
        ),
    ]
