# Generated by Django 2.2.4 on 2020-07-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_institutionconfig_max_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='identitydocument',
            name='modified_for_1c',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
