# Generated by Django 2.2.4 on 2019-08-28 11:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20190828_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyForm',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=500, null=True, verbose_name='Название')),
                ('name_kz', models.CharField(max_length=500, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=500, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Форма обучения',
                'verbose_name_plural': 'Формы обучения',
            },
        ),
    ]
