# Generated by Django 2.2.4 on 2019-09-03 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0006_educationbase_educationprogram_preparationlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcadPeriod',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Академический период',
                'verbose_name_plural': 'Академические периоды',
            },
        ),
        migrations.CreateModel(
            name='AcadPeriodType',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид академического периода',
                'verbose_name_plural': 'Вид академического периода',
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='LoadType',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид нагрузки',
                'verbose_name_plural': 'Виды нагрузок',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(max_length=100, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Направление подготовки',
                'verbose_name_plural': 'Направления подготовки',
            },
        ),
        migrations.CreateModel(
            name='StudyPeriod',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('start', models.PositiveSmallIntegerField(verbose_name='Начало')),
                ('end', models.PositiveSmallIntegerField(verbose_name='Окончание')),
            ],
            options={
                'verbose_name': 'Учебный период',
                'verbose_name_plural': 'Учебные периоды',
            },
        ),
        migrations.CreateModel(
            name='TeacherDiscipline',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Discipline', verbose_name='Дисциплина')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Language', verbose_name='Язык преподавания')),
                ('load_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.LoadType', verbose_name='Вид нагрузки')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Закрепление дисциплин',
                'verbose_name_plural': 'Закрепление дисциплин',
            },
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('cathedra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Cathedra', verbose_name='Выпускаюшая кафедра')),
                ('education_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.EducationProgram', verbose_name='Образовательная программа')),
                ('education_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to='organizations.EducationType', verbose_name='Вид образования')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Faculty', verbose_name='Факультет')),
                ('on_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.EducationType', verbose_name='На базе')),
                ('preparation_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.PreparationLevel', verbose_name='Уровень подготовки')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Speciality', verbose_name='Направление подготовки')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
                ('study_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.StudyForm', verbose_name='Форма обучения')),
                ('study_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.StudyPeriod', verbose_name='Учебный период')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
            },
        ),
        migrations.CreateModel(
            name='StudentDiscipline',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('hours', models.FloatField(verbose_name='Часы')),
                ('acad_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.AcadPeriod', verbose_name='Академический период')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Discipline', verbose_name='Дисциплина')),
                ('load_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.LoadType', verbose_name='Вид нагрузки')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.StudyPlan', verbose_name='Учебный план')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Дисциплина студента',
                'verbose_name_plural': 'Дисциплины студента',
            },
        ),
        migrations.AddField(
            model_name='acadperiod',
            name='period_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.AcadPeriodType', verbose_name='Вид академического периода'),
        ),
    ]
