# Generated by Django 2.2.4 on 2019-09-04 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_studentdiscipline_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='cathedra',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Faculty', verbose_name='Факультет'),
        ),
    ]
