# Generated by Django 2.2.4 on 2019-09-04 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_cathedra_faculty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdiscipline',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentdiscipline',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='studyplan',
            name='student',
        ),
    ]
