# Generated by Django 2.2.4 on 2019-09-04 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0015_auto_20190904_1432'),
        ('organizations', '0012_auto_20190904_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='educations', to='portal_users.Profile', verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='studentdiscipline',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_disciplines', to='portal_users.Profile', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='studentdiscipline',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='teacherdiscipline',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Преподаватель'),
        ),
    ]
