# Generated by Django 2.2.4 on 2019-09-04 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_auto_20190904_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdiscipline',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Преподаватель'),
        ),
    ]
