# Generated by Django 2.2.4 on 2019-09-04 11:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_auto_20190904_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadType2',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип нагрузки',
                'verbose_name_plural': 'Типы нагрузок',
            },
        ),
        migrations.RemoveField(
            model_name='teacherdiscipline',
            name='load_type',
        ),
        migrations.AddField(
            model_name='teacherdiscipline',
            name='study_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.StudyPeriod', verbose_name='Учебный период'),
        ),
        migrations.AddField(
            model_name='loadtype',
            name='load_type2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.LoadType2', verbose_name='Тип нагрузки'),
        ),
        migrations.AddField(
            model_name='teacherdiscipline',
            name='load_type2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.LoadType2', verbose_name='Тип нагрузки'),
        ),
    ]
