# Generated by Django 2.2.4 on 2019-09-05 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_auto_20190904_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Language', verbose_name='Язык обучения'),
        ),
    ]
