# Generated by Django 2.2.4 on 2019-09-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_auto_20190905_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='year',
        ),
    ]
