# Generated by Django 2.2.4 on 2019-09-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_auto_20190905_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='number',
            field=models.CharField(max_length=100, null=True, verbose_name='Номер'),
        ),
    ]
