# Generated by Django 2.2.4 on 2019-09-06 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_studyplan_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_groups', to='portal_users.Profile', verbose_name='Эдвайзер'),
        ),
    ]
