# Generated by Django 2.2.4 on 2019-09-06 09:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0024_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='description_kk',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='description_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='organizations.Discipline', verbose_name='Дисциплина')),
                ('required_discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Discipline', verbose_name='Требуемая дисциплина')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Speciality', verbose_name='Направление подготовки')),
                ('study_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.StudyPeriod', verbose_name='Учебный период')),
            ],
            options={
                'verbose_name': 'Пререквизит',
                'verbose_name_plural': 'Пререквизиты',
            },
        ),
        migrations.CreateModel(
            name='Postrequisite',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('available_discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Discipline', verbose_name='Доступная дисциплина')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postrequisites', to='organizations.Discipline', verbose_name='Дисциплина')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Speciality', verbose_name='Направление подготовки')),
                ('study_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.StudyPeriod', verbose_name='Учебный период')),
            ],
            options={
                'verbose_name': 'Постреквизит',
                'verbose_name_plural': 'Постреквизиты',
            },
        ),
    ]
