# Generated by Django 2.2.4 on 2019-09-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0025_auto_20190906_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='is_language',
            field=models.BooleanField(default=False, verbose_name='Языковая дисциплина?'),
        ),
    ]
