# Generated by Django 2.2.4 on 2019-09-09 06:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0016_auto_20190905_1420'),
        ('organizations', '0026_discipline_is_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDisciplineStatus',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус при выборе препода',
                'verbose_name_plural': 'Статусы при выборе препода',
            },
        ),
        migrations.AddField(
            model_name='studentdiscipline',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='edited_student_disciplines', to='portal_users.Profile', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='studentdiscipline',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.StudentDisciplineStatus', verbose_name='Статус'),
        ),
    ]
