# Generated by Django 2.2.4 on 2019-09-10 03:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0016_auto_20190905_1420'),
        ('organizations', '0027_auto_20190909_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDisciplineInfo',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Не выбрал'), (2, 'Выбрал для всех дисцилин')], verbose_name='Статус')),
                ('acad_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.AcadPeriod', verbose_name='Академический период')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Студент')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.StudyPlan', verbose_name='Учебный план')),
            ],
            options={
                'verbose_name': 'Инфо о выборе студента',
                'verbose_name_plural': 'Инфо о выбора студента',
            },
        ),
    ]
