# Generated by Django 2.2.4 on 2019-09-10 05:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0028_studentdisciplineinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDisciplineInfoStatus',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус об общем выборе препода',
                'verbose_name_plural': 'Статус об общем выборе препода',
            },
        ),
        migrations.RemoveField(
            model_name='studentdisciplineinfo',
            name='status',
        ),
    ]
