# Generated by Django 2.2.4 on 2019-09-10 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0030_studentdisciplineinfo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyplan',
            name='study_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.StudyPeriod', verbose_name='Период обучения'),
        ),
        migrations.AlterUniqueTogether(
            name='studentdisciplineinfo',
            unique_together={('acad_period', 'study_plan')},
        ),
    ]
