# Generated by Django 2.2.4 on 2019-09-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0031_auto_20190910_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationprogram',
            name='code',
            field=models.CharField(default='', max_length=100, verbose_name='Код'),
        ),
    ]
