# Generated by Django 2.2.4 on 2019-09-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0033_auto_20190913_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdisciplinestatus',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Номер'),
        ),
    ]
