# Generated by Django 2.2.4 on 2019-09-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0034_studentdisciplinestatus_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='entry_date',
            field=models.DateField(null=True, verbose_name='Дата поступления в ВУЗ'),
        ),
    ]
