# Generated by Django 2.2.4 on 2019-09-18 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0035_studyplan_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdiscipline',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.Language', verbose_name='Язык'),
        ),
    ]
