# Generated by Django 2.2.4 on 2019-09-26 11:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0037_auto_20190918_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationProgramGroup',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('code', models.CharField(default='', max_length=100, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Группа образовательных программ',
                'verbose_name_plural': 'Группы образовательных программ',
            },
        ),
        migrations.AddField(
            model_name='educationprogram',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.EducationProgramGroup', verbose_name='Группа ОП'),
        ),
    ]
