# Generated by Django 2.2.4 on 2019-09-27 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0023_remove_profile_entry_date'),
        ('organizations', '0038_auto_20190926_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_study_plans', to='portal_users.Profile', verbose_name='Эдвайзер'),
        ),
    ]
