# Generated by Django 2.2.4 on 2019-10-01 06:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0039_studyplan_advisor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='supervisor',
        ),
        migrations.CreateModel(
            name='StudyYearCourse',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('course', models.PositiveIntegerField(verbose_name='Курс')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.StudyPlan', verbose_name='Учебный план')),
                ('study_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.StudyPeriod', verbose_name='Учебный год')),
            ],
            options={
                'verbose_name': 'Учебный Год - Курс',
                'verbose_name_plural': 'Учебный Год - Курс',
            },
        ),
    ]
