# Generated by Django 2.2.4 on 2019-10-03 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0023_remove_profile_entry_date'),
        ('organizations', '0043_auto_20191002_1739'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studyplan',
            unique_together={('student', 'group')},
        ),
    ]
