# Generated by Django 2.2.4 on 2019-10-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0044_auto_20191003_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyperiod',
            name='is_study_year',
            field=models.BooleanField(default=False, verbose_name='Учебный год'),
        ),
    ]
