# Generated by Django 2.2.4 on 2019-10-08 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0023_remove_profile_entry_date'),
        ('organizations', '0046_auto_20191008_0922'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studyplan',
            unique_together={('student', 'group', 'education_program')},
        ),
    ]
