# Generated by Django 2.2.4 on 2019-10-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0049_studentdiscipline_study_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='acadperiod',
            name='number',
            field=models.IntegerField(default=0, verbose_name='Номер'),
        ),
    ]
