# Generated by Django 2.2.4 on 2019-10-22 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0050_acadperiod_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acadperiod',
            options={'ordering': ('number',), 'verbose_name': 'Академический период', 'verbose_name_plural': 'Академические периоды'},
        ),
    ]
