# Generated by Django 2.2.4 on 2019-10-30 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0053_disciplinecomponent_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinecomponent',
            name='short_name_en',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='disciplinecomponent',
            name='short_name_kk',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='disciplinecomponent',
            name='short_name_ru',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
