# Generated by Django 2.2.4 on 2019-10-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0054_auto_20191030_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='code',
        ),
        migrations.AddField(
            model_name='studentdiscipline',
            name='discipline_code',
            field=models.CharField(default='', max_length=100, verbose_name='Код дисциплины'),
        ),
    ]
