# Generated by Django 2.2.4 on 2019-11-01 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0055_auto_20191031_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdiscipline',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_disciplines', to='organizations.DisciplineComponent', verbose_name='Компонент дисциплины'),
        ),
    ]
