# Generated by Django 2.2.4 on 2019-11-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0057_auto_20191104_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinecycle',
            name='short_name_en',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='Краткое название'),
        ),
        migrations.AddField(
            model_name='disciplinecycle',
            name='short_name_kk',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='Краткое название'),
        ),
        migrations.AddField(
            model_name='disciplinecycle',
            name='short_name_ru',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='Краткое название'),
        ),
    ]
