# Generated by Django 2.2.4 on 2019-11-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0058_auto_20191104_1114'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
