# Generated by Django 2.2.4 on 2019-12-05 11:02

from django.db import migrations


def generate_student_discipline_statuses(apps, schema_editor):
    StudentDisciplineStatus = apps.get_model('organizations', 'StudentDisciplineStatus')

    student_discipline_status_list = [
        {
            "uid": "5237bbea-f230-4cef-9b37-8fb6ad42f26b",
            "name_ru": "не выбран",
            "name_kk": "тандалмаган",
            "name_en": "not chosen",
            "number": 1,
        },
        {
            "uid": "c8840584-ad29-4059-adba-2bc68e211747",
            "name_ru": "выбран",
            "name_kk": "тандалган",
            "name_en": "chosen",
            "number": 2,
        },
        {
            "uid": "d561b14f-9668-404e-9401-ead972327535",
            "name_ru": "отклонен",
            "name_kk": "кайтарылган",
            "name_en": "cancelled",
            "number": 3,
        },
        {
            "uid": "a56a0ab6-1251-428a-b041-943dcfed4b68",
            "name_ru": "утвержден",
            "name_kk": "расталган",
            "name_en": "confirmed",
            "number": 4,
        },
        {
            "uid": "1aa2dea0-8535-43f9-a1c2-494f966224c3",
            "name_ru": "изменен",
            "name_kk": "өзгерген",
            "name_en": "changed",
            "number": 5,
        },
    ]

    student_discipline_status = {
        "chosen": "c8840584-ad29-4059-adba-2bc68e211747",
        "not_chosen": "5237bbea-f230-4cef-9b37-8fb6ad42f26b",
        "rejected": "d561b14f-9668-404e-9401-ead972327535",
        "confirmed": "a56a0ab6-1251-428a-b041-943dcfed4b68",
        "changed": "1aa2dea0-8535-43f9-a1c2-494f966224c3"
    }

    for item in student_discipline_status_list:
        StudentDisciplineStatus.objects.create(**item)


def generate_student_discipline_info_statuses(apps, schema_editor):
    StudentDisciplineInfoStatus = apps.get_model('organizations', 'StudentDisciplineInfoStatus')

    student_discipline_info_status_list = [
        {
            "uid": "9338609e-80a5-48dd-9c7f-1b009b468a10",
            "name_ru": "Утвержден",
            "name_kk": "Расталған",
            "name_en": "Confirmed",
            # "number": ,
        },
        {
            "uid": "6284e6c1-15b2-4748-ad1a-589d7da87cd2",
            "name_ru": "Отклонен",
            "name_kk": "Қайтарылған",
            "name_en": "Rejected",
            # "number": ,
        },
        {
            "uid": "4f451e25-b3cb-4ab0-a55e-a3b3b3582529",
            "name_ru": "Выбрал",
            "name_kk": "Тандаған",
            "name_en": "Chosen",
            # "number": ,
        },
        {
            "uid": "449803da-e38f-4dbf-8ef9-a7b3ef0133ef",
            "name_ru": "Выбирает",
            "name_kk": "Таңдау үстінде",
            "name_en": "Choosing",
            # "number": ,
        },
        {
            "uid": "078f15c8-1bbc-46b4-8904-e31599078a83",
            "name_ru": "Выбор не начат",
            "name_kk": "Таңдау басталмаған",
            "name_en": "Not started choosing",
            # "number": ,
        },
    ]

    student_discipline_info_status = {
        "not_started": "078f15c8-1bbc-46b4-8904-e31599078a83",
        "choosing": "449803da-e38f-4dbf-8ef9-a7b3ef0133ef",
        "chosen": "4f451e25-b3cb-4ab0-a55e-a3b3b3582529",
        "confirmed": "9338609e-80a5-48dd-9c7f-1b009b468a10",
        "rejected": "6284e6c1-15b2-4748-ad1a-589d7da87cd2"
    }

    for item in student_discipline_info_status_list:
        StudentDisciplineInfoStatus.objects.create(**item)


def generate_lesson_statuses(apps, schema_editor):
    LessonStatus = apps.get_model('schedules', 'LessonStatus')

    lesson_statuses_list = [
        {
            "uid": 'd986b84d-e6a3-4d64-a470-167b9da79684',
            "name_ru": "Состоялось",
            "name_kk": "Өтізілген",
            "name_en": "Executed",
            # "number": ,
        },
        {
            "uid": '292859e6-7045-40b5-8bb8-fa6bef62b0eb',
            "name_ru": "Заменено",
            "name_kk": "Ауыстырылған",
            "name_en": "Replaced",
            # "number": ,
        },
        {
            "uid": '1c6c9d3e-8b07-4602-bf5c-a0567d406300',
            "name_ru": "Запланировано",
            "name_kk": "Жоспарланған",
            "name_en": "Planned",
            # "number": ,
        },
        {
            "uid": '0b5b5427-f26a-48e0-a868-0695a7d23cb9',
            "name_ru": "Отменено",
            "name_kk": "Тоқтатылған",
            "name_en": "Cancelled",
            # "number": ,
        },
    ]

    lesson_statuses = {
        'executed': 'd986b84d-e6a3-4d64-a470-167b9da79684',  # Состоялось
        'replaced': '292859e6-7045-40b5-8bb8-fa6bef62b0eb',  # Заменено
        'planned': '1c6c9d3e-8b07-4602-bf5c-a0567d406300',  # Запланировано
        'canceled': '0b5b5427-f26a-48e0-a868-0695a7d23cb9'  # Отменено
    }

    for item in lesson_statuses_list:
        LessonStatus.objects.create(**item)


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0059_delete_student'),
    ]

    operations = [
        migrations.RunPython(generate_student_discipline_statuses),
        migrations.RunPython(generate_student_discipline_info_statuses),
        # Эта функция по генерации статусов не работает без дампа БД.
        migrations.RunPython(generate_lesson_statuses),
    ]
