# Generated by Django 2.2.4 on 2019-12-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0060_auto_20191205_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadtype2',
            name='uid_1c',
            field=models.CharField(default='', max_length=200, verbose_name='УИД 1С'),
        ),
    ]
