# Generated by Django 2.2.4 on 2019-12-09 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0062_loadtype_parent_uid_1c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='headman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_groups', to='portal_users.Profile', verbose_name='Староста'),
        ),
        migrations.AlterField(
            model_name='group',
            name='kurator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Куратор'),
        ),
    ]
