# Generated by Django 2.2.4 on 2019-12-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0064_auto_20191210_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherdiscipline',
            name='load_type2_uid_1c',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='УИД 1С Типа нагрузки'),
        ),
    ]
