# Generated by Django 2.2.4 on 2019-12-11 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0042_auto_20191211_1256'),
        ('common', '0016_auto_20191211_1431'),
        ('organizations', '0066_auto_20191211_1009'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='education',
            unique_together={('profile', 'document_type', 'edu_type', 'serial_number', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='postrequisite',
            unique_together={('study_period', 'discipline', 'available_discipline', 'speciality')},
        ),
        migrations.AlterUniqueTogether(
            name='prerequisite',
            unique_together={('study_period', 'discipline', 'required_discipline', 'speciality')},
        ),
        migrations.AlterUniqueTogether(
            name='studentdiscipline',
            unique_together={('student', 'study_plan', 'acad_period', 'discipline_code', 'discipline', 'load_type', 'hours', 'language', 'cycle', 'study_year')},
        ),
    ]
