# Generated by Django 2.2.4 on 2019-12-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0067_auto_20191211_1431'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loadtype2',
            unique_together={('name_ru',)},
        ),
    ]
