# Generated by Django 2.2.4 on 2019-12-12 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0068_auto_20191211_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='is_subgroup',
            field=models.BooleanField(default=False, verbose_name='Подгруппа'),
        ),
        migrations.AddField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='organizations.Group', verbose_name='Родитель'),
        ),
    ]
