# Generated by Django 2.2.4 on 2019-12-13 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0069_auto_20191212_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acadperiod',
            name='period_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.AcadPeriodType', verbose_name='Вид академического периода'),
        ),
    ]
