# Generated by Django 2.2.4 on 2019-12-20 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0072_auto_20191220_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdiscipline',
            old_name='number',
            new_name='uid_1c',
        ),
    ]
