# Generated by Django 2.2.4 on 2019-12-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0073_auto_20191220_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentdiscipline',
            old_name='uid_1c',
            new_name='study_plan_uid_1c',
        ),
    ]
