# Generated by Django 2.2.4 on 2019-12-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0075_auto_20191220_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdiscipline',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Отправлен в 1С'),
        ),
    ]
