# Generated by Django 2.2.4 on 2019-12-31 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0049_profile_password_changed'),
        ('organizations', '0077_studentdiscipline_uid_1c'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='studentdiscipline',
            index_together={('discipline', 'study_plan', 'study_year', 'acad_period')},
        ),
        migrations.AlterIndexTogether(
            name='studyplan',
            index_together={('faculty', 'cathedra', 'education_program', 'speciality', 'group', 'advisor', 'student')},
        ),
    ]
