# Generated by Django 2.2.4 on 2020-01-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0078_auto_20191231_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdiscipline',
            name='sent',
            field=models.NullBooleanField(default=False, verbose_name='Отправлен в 1С'),
        ),
    ]
