# Generated by Django 2.2.4 on 2020-01-04 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0079_auto_20200104_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdiscipline',
            name='uid_1c',
            field=models.CharField(blank=True, default='', help_text='придет, после выгрузки в 1С', max_length=100, null=True, verbose_name='УИД документа-аналога в 1С'),
        ),
    ]
