# Generated by Django 2.2.4 on 2020-01-15 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0082_studentdiscipline_uuid1c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherdiscipline',
            old_name='uid_1c',
            new_name='uuid1c',
        ),
    ]
