# Generated by Django 2.2.4 on 2020-01-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0083_auto_20200115_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrequisite',
            name='uuid1c',
            field=models.CharField(default='', editable=False, max_length=100, verbose_name='Уид 1С'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='uuid1c',
            field=models.CharField(default='', editable=False, max_length=100, verbose_name='Уид 1С'),
        ),
        migrations.AlterField(
            model_name='studentdiscipline',
            name='uuid1c',
            field=models.CharField(default='', editable=False, max_length=100, verbose_name='Уид 1С'),
        ),
        migrations.AlterField(
            model_name='teacherdiscipline',
            name='uuid1c',
            field=models.CharField(default='', editable=False, max_length=100, verbose_name='Уид 1С'),
        ),
    ]
