# Generated by Django 2.2.4 on 2020-01-17 11:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0084_auto_20200115_1006'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='ControlForm',
        #     fields=[
        #         ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
        #         ('is_active', models.BooleanField(default=True)),
        #         ('created', models.DateTimeField(auto_now_add=True)),
        #         ('updated', models.DateTimeField(auto_now=True)),
        #         ('deleted', models.DateTimeField(blank=True, null=True)),
        #         ('name', models.CharField(max_length=800, verbose_name='Название')),
        #         ('name_ru', models.CharField(max_length=800, null=True, verbose_name='Название')),
        #         ('name_kk', models.CharField(max_length=800, null=True, verbose_name='Название')),
        #         ('name_en', models.CharField(max_length=800, null=True, verbose_name='Название')),
        #         ('is_exam', models.BooleanField(default=False, verbose_name='Является экзаменом')),
        #         ('is_course_work', models.BooleanField(default=False, verbose_name='Является курсовой работой')),
        #         ('is_gos_exam', models.BooleanField(default=False, verbose_name='Является гос экзаменом')),
        #         ('is_diploma', models.BooleanField(default=False, verbose_name='Является государственным экзаменом')),
        #     ],
        #     options={
        #         'verbose_name': 'Форма контроля',
        #         'verbose_name_plural': 'Формы контроля',
        #     },
        # ),
    ]
