# Generated by Django 2.2.4 on 2020-01-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0087_auto_20200121_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlform',
            name='is_diploma',
            field=models.BooleanField(default=False, verbose_name='Является защитой диплома/диссертации '),
        ),
        migrations.AlterUniqueTogether(
            name='disciplinecreditcontrolform',
            unique_together={('discipline_credit', 'control_form')},
        ),
    ]
