# Generated by Django 2.2.4 on 2020-01-22 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0051_auto_20200115_1436'),
        ('organizations', '0088_auto_20200122_0943'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentdiscipline',
            unique_together={('student', 'study_plan_uid_1c', 'acad_period', 'discipline', 'load_type', 'hours')},
        ),
    ]
