# Generated by Django 2.2.4 on 2020-01-24 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0051_auto_20200115_1436'),
        ('organizations', '0089_auto_20200124_1010'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='studentdiscipline',
        #     unique_together={('student', 'uuid1c')},
        # ),
    ]
