# Generated by Django 2.2.4 on 2020-01-28 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0091_auto_20200128_1033'),
        ('organizations', '0092_auto_20200128_1317'),
    ]

    operations = [
    ]
