# Generated by Django 2.2.4 on 2020-01-28 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0093_merge_20200128_1444'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='disciplinecredit',
        #     name='control_form',
        # ),
    ]
