# Generated by Django 2.2.4 on 2020-01-29 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0053_auto_20200128_1317'),
        ('organizations', '0094_remove_disciplinecredit_control_form'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='disciplinecredit',
        #     name='control_form',
        # ),
        migrations.AddField(
            model_name='faculty',
            name='dekan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Декан'),
        ),
    ]
