# Generated by Django 2.2.4 on 2020-01-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0095_auto_20200129_1522'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='disciplinecredit',
        #     name='control_form',
        # ),
        migrations.AddField(
            model_name='preparationlevel',
            name='shifr',
            field=models.CharField(max_length=500, null=True, verbose_name='Шифр'),
        ),
    ]
