# Generated by Django 2.2.4 on 2020-02-03 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0096_auto_20200129_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinecredit',
            name='control_form',
        ),
    ]
