# Generated by Django 2.2.4 on 2020-02-04 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0097_remove_disciplinecredit_control_form'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='studentdiscipline',
        #     unique_together={('student',
        #                       # 'uuid1c',
        #                       'study_plan_uid_1c',
        #                       'acad_period',
        #                       'discipline_code',
        #                       'discipline',
        #                       'load_type',
        #                       'hours',
        #                       'language',
        #                       'cycle',
        #                       'study_year',)},
        # ),
    ]
