# Generated by Django 2.2.4 on 2020-02-04 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0053_auto_20200128_1317'),
        ('organizations', '0099_auto_20200204_1453'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='studentdiscipline',
        #     unique_together={('student', 'uuid1c')},
        # ),
    ]
