# Generated by Django 2.2.4 on 2020-02-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0102_auto_20200204_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisite',
            name='uuid1c',
            field=models.CharField(editable=False, max_length=100, null=True, unique=True, verbose_name='Уид 1С'),
        ),
        # migrations.AlterUniqueTogether(
        #     name='prerequisite',
        #     unique_together={('study_period', 'discipline', 'required_discipline', 'speciality')},
        # ),
    ]
