# Generated by Django 2.2.4 on 2020-02-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0103_auto_20200204_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prerequisite',
            name='uuid1c',
            field=models.CharField(editable=False, max_length=100, null=True, verbose_name='Уид 1С'),
        ),
    ]
