# Generated by Django 2.2.4 on 2020-02-10 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0053_auto_20200128_1317'),
        ('organizations', '0107_auto_20200205_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinecredit',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='disciplinecredit',
            name='study_plan_uid_1c',
            field=models.CharField(max_length=100, null=True, verbose_name='uid 1c учебного плана'),
        ),
    ]
