# Generated by Django 2.2.4 on 2020-02-10 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0053_auto_20200128_1317'),
        ('organizations', '0108_auto_20200210_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinecredit',
            name='uuid1c',
            field=models.CharField(editable=False, max_length=100, verbose_name='Уид 1С'),
        ),
        migrations.AlterUniqueTogether(
            name='disciplinecredit',
            unique_together={('uuid1c', 'student')},
        ),
    ]
