# Generated by Django 2.2.4 on 2020-02-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0110_auto_20200214_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='EroroText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст ошибки')),
            ],
            options={
                'verbose_name': 'текст ошибки',
                'verbose_name_plural': 'текста ошибки',
            },
        ),
    ]
