# Generated by Django 2.2.4 on 2020-03-10 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0055_auto_20200225_1056'),
        ('organizations', '0111_erorotext'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinecredit',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discipline_credit_status', to='organizations.StudentDisciplineStatus', verbose_name='Статус диспцилины'),
        ),
        migrations.AddField(
            model_name='disciplinecredit',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discipline_credit_teacher', to='portal_users.Profile', verbose_name='Преподаватель'),
        ),
    ]
