# Generated by Django 2.2.4 on 2020-03-20 10:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0112_auto_20200312_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='avg_mark',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(3.7)], verbose_name='Средняя оценка (не выще 3.7)'),
        ),
        migrations.AddField(
            model_name='education',
            name='institute_text',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Учебное заведение (текстовое представление)'),
        ),
        migrations.AddField(
            model_name='education',
            name='is_altyn_belgi_holder',
            field=models.BooleanField(default=False, verbose_name='Держатель знака «Алтын белгі»'),
        ),
        migrations.AddField(
            model_name='education',
            name='is_nerd',
            field=models.BooleanField(default=False, verbose_name='Закончил учебу с отличием'),
        ),
        migrations.AddField(
            model_name='education',
            name='no_institute',
            field=models.BooleanField(default=False, verbose_name='Моего УЗ нет в списке'),
        ),
        migrations.AddField(
            model_name='education',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Speciality', verbose_name='Специальность'),
        ),
        migrations.AddField(
            model_name='education',
            name='study_form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.StudyForm', verbose_name='Форма обучения'),
        ),
    ]
