# Generated by Django 2.2.4 on 2020-03-26 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0006_remove_testcert_disciplines'),
        ('organizations', '0113_auto_20200320_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.DocScan'),
        ),
    ]
