# Generated by Django 2.2.4 on 2020-03-27 09:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0112_auto_20200312_1209'),
        ('organizations', '0113_remove_disciplinecredit_teacher'),
    ]

    operations = [
    ]
