# Generated by Django 2.2.4 on 2020-03-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0115_disciplinecredit_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinecredit',
            name='sent',
            field=models.NullBooleanField(default=False, verbose_name='Отправлен в 1С'),
        ),
    ]
