# Generated by Django 2.2.4 on 2020-03-31 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('organizations', '0116_disciplinecredit_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinecredit',
            name='uid_1c',
            field=models.CharField(blank=True, default='', help_text='придет, после выгрузки в 1С', max_length=100,
                                   null=True, verbose_name='УИД документа-аналога в 1С'),
        ),
    ]
