# Generated by Django 2.2.4 on 2020-05-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0117_disciplinecredit_uid_1c'),
        ('organizations', '0116_auto_20200403_1909'),
    ]

    operations = [
    ]
