# Generated by Django 2.2.4 on 2020-04-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0059_merge_20200410_1700'),
        ('organizations', '0118_merge_20200410_1700'),
    ]

    operations = [
        # django.db.utils.ProgrammingError: column "teacher_id" of relation "organizations_disciplinecredit" already exists
        # migrations.AddField(
        #     model_name='disciplinecredit',
        #     name='teacher',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discipline_credit_teacher', to='portal_users.Profile', verbose_name='Преподаватель'),
        # ),
    ]
