# Generated by Django 2.2.4 on 2020-04-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0119_disciplinecredit_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinecredit',
            name='teacher',
        ),
    ]
