# Generated by Django 2.2.4 on 2020-05-07 05:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0121_education_is_nis_graduate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='avg_mark',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(4.0)], verbose_name='Средняя оценка (не выще 3.7)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Speciality', verbose_name='Специальность'),
        ),
    ]
