# Generated by Django 2.2.4 on 2020-05-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0118_merge_20200519_1138'),
        ('organizations', '0122_auto_20200507_1152'),
    ]

    operations = [
    ]
