# Generated by Django 2.2.4 on 2020-05-21 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_auto_20200521_1056'),
        ('organizations', '0123_merge_20200520_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='scan',
        ),
        migrations.AddField(
            model_name='education',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Document'),
        ),
    ]
