# Generated by Django 2.2.4 on 2020-05-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0123_merge_20200520_0756'),
        ('organizations', '0118_merge_20200430_0917'),
    ]

    operations = [
    ]
