# Generated by Django 2.2.4 on 2020-05-22 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0124_auto_20200521_1056'),
        ('organizations', '0124_merge_20200520_0945'),
    ]

    operations = [
    ]
