# Generated by Django 2.2.4 on 2020-05-26 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0125_merge_20200522_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='is_nerd',
            new_name='is_flawless_graduate',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='is_altyn_belgi_holder',
            new_name='is_honorable_graduate',
        ),
    ]
