# Generated by Django 2.2.4 on 2020-06-12 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0127_auto_20200609_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplinegroup',
            options={'verbose_name': 'Группа дисциплин', 'verbose_name_plural': 'Группы дисциплин'},
        ),
    ]
