# Generated by Django 2.2.4 on 2020-07-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0130_education_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='uid_1c',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='UID документа в 1С'),
        ),
    ]
