# Generated by Django 2.2.4 on 2020-07-24 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0131_education_uid_1c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdiscipline',
            name='study_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plan', to='organizations.StudyPlan', verbose_name='Учебный план'),
        ),
    ]
