# Generated by Django 2.2.4 on 2020-07-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0132_auto_20200724_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='modified_for_1c',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
