# Generated by Django 2.2.4 on 2020-07-29 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0133_education_modified_for_1c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='study_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.StudyForm', verbose_name='Форма обучения'),
        ),
    ]
