# Generated by Django 2.2.4 on 2020-08-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0134_auto_20200729_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdiscipline',
            name='acad_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acad_period', to='organizations.AcadPeriod', verbose_name='Академический период'),
        ),
    ]
