# Generated by Django 2.2.4 on 2020-08-03 05:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0134_auto_20200729_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='education_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.EducationProgram', verbose_name='Образовательные программы'),
        ),
        migrations.AlterField(
            model_name='education',
            name='avg_mark',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Средняя оценка (не выше 5.0)'),
        ),
    ]
