# Generated by Django 2.2.4 on 2020-08-04 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0135_auto_20200803_1153'),
        ('organizations', '0136_auto_20200804_1723'),
    ]

    operations = [
    ]
