# Generated by Django 2.2.4 on 2020-08-04 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0137_merge_20200804_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdiscipline',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline', to='organizations.Discipline', verbose_name='Дисциплина'),
        ),
    ]
