# Generated by Django 2.2.4 on 2019-11-29 16:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C1Object',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('model', models.CharField(default='', max_length=100, verbose_name='Модель django')),
                ('is_related', models.BooleanField(default=False, verbose_name='Это связанная модель')),
            ],
            options={
                'verbose_name': 'Объект интеграции с 1с',
                'verbose_name_plural': 'Объекты интеграции с 1с',
            },
        ),
        migrations.CreateModel(
            name='C1ObjectCompare',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('c1', models.CharField(default='', max_length=100, verbose_name='Поле 1С')),
                ('django', models.CharField(default='', max_length=100, verbose_name='Поле Django')),
                ('main_field', models.BooleanField(default=False, verbose_name='Ведущее поле')),
                ('is_binary_data', models.BooleanField(default=False, verbose_name='Двоичные данные')),
                ('c1_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c1.C1Object', verbose_name='Объект интеграции')),
            ],
            options={
                'verbose_name': 'Поле',
                'verbose_name_plural': 'Поля',
            },
        ),
    ]
