# Generated by Django 2.2.4 on 2020-03-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0003_auto_20200128_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c1object',
            name='model',
            field=models.CharField(default='', max_length=100, verbose_name='Модель Джанго'),
        ),
    ]
