# Generated by Django 2.2.4 on 2020-04-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0003_auto_20200128_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='c1object',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='c1objectcompare',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
