# Generated by Django 2.2.4 on 2020-05-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0004_auto_20200403_1152'),
        ('c1', '0004_auto_20200326_0457'),
    ]

    operations = [
    ]
