# Generated by Django 2.2.4 on 2020-05-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0005_merge_20200410_1700'),
        ('c1', '0005_merge_20200519_1138'),
    ]

    operations = [
    ]
