# Generated by Django 2.2.4 on 2020-05-20 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0005_merge_20200430_0917'),
        ('c1', '0006_merge_20200520_0756'),
    ]

    operations = [
    ]
