# Generated by Django 2.2.4 on 2020-06-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c1', '0007_merge_20200520_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c1object',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='c1objectcompare',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
