# Generated by Django 2.2.4 on 2020-07-07 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repetitiontypes',
            options={'verbose_name': ('Тип повторения события',), 'verbose_name_plural': ('Тип повторения событий',)},
        ),
    ]
