# Generated by Django 2.2.4 on 2020-07-09 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0002_auto_20200707_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events_participants', to='portal_users.Profile', verbose_name='Участники события'),
        ),
    ]
