# Generated by Django 2.2.4 on 2020-07-13 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_api', '0004_auto_20200713_0728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='roles',
        ),
    ]
