# Generated by Django 2.2.4 on 2020-07-28 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0037_institutionconfig_max_file_size'),
        ('calendar_api', '0005_remove_participants_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='files',
            field=models.ManyToManyField(blank=True, to='common.File', verbose_name='Файлы события'),
        ),
    ]
