# Generated by Django 2.2.4 on 2019-11-15 10:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0058_auto_20191104_1114'),
        ('portal_users', '0030_auto_20191112_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradingSystem',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Система оценивания',
                'verbose_name_plural': 'Системы оценивании',
            },
        ),
        migrations.CreateModel(
            name='LessonStatus',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус занятия',
                'verbose_name_plural': 'Статусы занятий',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип помещения',
                'verbose_name_plural': 'Типы помещений',
            },
        ),
        migrations.CreateModel(
            name='TimeWindow',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('from_time', models.TimeField(verbose_name='Время с')),
                ('to_time', models.TimeField(verbose_name='Время по')),
            ],
            options={
                'verbose_name': 'Временное окно',
                'verbose_name_plural': 'Временные окна',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('object_id', models.PositiveIntegerField()),
                ('capacity', models.IntegerField(verbose_name='Вместимость ')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='schedules.RoomType', verbose_name='Тип помещения')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('flow_uid', models.UUIDField(verbose_name='UID потока')),
                ('date', models.DateField(verbose_name='Дата занятия')),
                ('subject', models.CharField(blank=True, default='', max_length=500, verbose_name='Тема')),
                ('subject_ru', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Тема')),
                ('subject_kk', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Тема')),
                ('subject_en', models.CharField(blank=True, default='', max_length=500, null=True, verbose_name='Тема')),
                ('replacement', models.BooleanField(default=False, verbose_name='Замена')),
                ('acad_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.AcadPeriod', verbose_name='Академический период')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Room', verbose_name='Аудитория')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Discipline', verbose_name='Дисциплина')),
                ('grading_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.GradingSystem', verbose_name='Система оценивания')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Group', verbose_name='Группа')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Language', verbose_name='Язык преподавания')),
                ('load_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.LoadType2')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.LessonStatus', verbose_name='Статус занятия')),
                ('study_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.StudyPeriod', verbose_name='Учебный год')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Преподаватель')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.TimeWindow', verbose_name='Время занятия')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
    ]
