# Generated by Django 2.2.4 on 2019-11-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='replacement',
        ),
    ]
