# Generated by Django 2.2.4 on 2019-11-20 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_remove_lesson_replacement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='object_id',
        ),
    ]
