# Generated by Django 2.2.4 on 2019-11-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_remove_room_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='object_id',
            field=models.UUIDField(null=True),
        ),
    ]
