# Generated by Django 2.2.4 on 2019-11-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0058_auto_20191104_1114'),
        ('schedules', '0004_room_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='group',
        ),
        migrations.AddField(
            model_name='lesson',
            name='groups',
            field=models.ManyToManyField(to='organizations.Group', verbose_name='Группы'),
        ),
    ]
