# Generated by Django 2.2.4 on 2019-11-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0030_auto_20191112_1132'),
        ('schedules', '0005_auto_20191120_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='teacher',
        ),
        migrations.AddField(
            model_name='lesson',
            name='teachers',
            field=models.ManyToManyField(to='portal_users.Profile', verbose_name='Преподаватели'),
        ),
    ]
