# Generated by Django 2.2.4 on 2019-11-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0006_auto_20191121_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='intermediate_control',
            field=models.BooleanField(default=False, verbose_name='Промежуточный контроль'),
        ),
    ]
