# Generated by Django 2.2.4 on 2019-11-22 08:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0030_auto_20191112_1132'),
        ('schedules', '0007_lesson_intermediate_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Название')),
                ('weight', models.FloatField(verbose_name='Вес оценки')),
                ('value_letter', models.CharField(max_length=200, verbose_name='Оценка по буквенной системе')),
                ('value_number', models.FloatField(verbose_name='Цифровой эквивалент')),
                ('value_traditional', models.CharField(max_length=200, verbose_name='Оценка по традиционной системе')),
                ('value_traditional_ru', models.CharField(max_length=200, null=True, verbose_name='Оценка по традиционной системе')),
                ('value_traditional_kk', models.CharField(max_length=200, null=True, verbose_name='Оценка по традиционной системе')),
                ('value_traditional_en', models.CharField(max_length=200, null=True, verbose_name='Оценка по традиционной системе')),
                ('grading_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.GradingSystem', verbose_name='Система оценивания')),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('missed', models.BooleanField(default=False, verbose_name='Отсутствовал')),
                ('reason', models.CharField(blank=True, default='', max_length=500, verbose_name='Причина отсутствия')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Lesson', verbose_name='Занятие')),
                ('mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.Mark', verbose_name='Оценка')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Успеваемость студента',
                'verbose_name_plural': 'Успеваемости студентов',
            },
        ),
    ]
