# Generated by Django 2.2.4 on 2019-11-26 04:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0058_auto_20191104_1114'),
        ('portal_users', '0030_auto_20191112_1132'),
        ('schedules', '0008_mark_studentperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalStatus',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Статус журнала',
                'verbose_name_plural': 'Статусы журналов',
            },
        ),
        migrations.AlterField(
            model_name='lesson',
            name='load_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.LoadType2', verbose_name='Тип нагрузки'),
        ),
        migrations.CreateModel(
            name='ElectronicJournal',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('study_start', models.DateField(verbose_name='Начало обучения')),
                ('study_end', models.DateField(verbose_name='Конец обучения')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.Discipline', verbose_name='Дисциплина')),
                ('load_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.LoadType2', verbose_name='Тип нагрузки')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.JournalStatus', verbose_name='Статус')),
                ('stud_disciplines', models.ManyToManyField(to='organizations.StudentDiscipline', verbose_name='Дисциплины студентов')),
                ('teachers', models.ManyToManyField(to='portal_users.Profile', verbose_name='Преподаватели')),
            ],
            options={
                'verbose_name': 'Электронный журнал',
                'verbose_name_plural': 'Электронные журналы',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='el_journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.ElectronicJournal', verbose_name='Электронный журнал'),
        ),
    ]
