# Generated by Django 2.2.4 on 2019-11-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_auto_20191126_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalstatus',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='journalstatus',
            name='name_kk',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='journalstatus',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
    ]
