# Generated by Django 2.2.4 on 2019-11-26 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_auto_20191126_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='el_journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedules.ElectronicJournal', verbose_name='Электронный журнал'),
        ),
    ]
