# Generated by Django 2.2.4 on 2019-11-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0013_auto_20191126_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingsystem',
            name='number',
            field=models.SmallIntegerField(default=0, verbose_name='Номер'),
        ),
    ]
