# Generated by Django 2.2.4 on 2019-11-27 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0030_auto_20191112_1132'),
        ('schedules', '0015_auto_20191127_0014'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentperformance',
            unique_together={('lesson', 'student')},
        ),
    ]
