# Generated by Django 2.2.4 on 2019-12-04 06:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0034_auto_20191203_1243'),
        ('schedules', '0018_auto_20191201_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformanceLog',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('missed', models.BooleanField(default=False, verbose_name='Отсутствовал')),
                ('reason', models.CharField(blank=True, default='', max_length=500, verbose_name='Причина отсутствия')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Автор')),
                ('mark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.Mark', verbose_name='Оценка')),
                ('stud_perf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.StudentPerformance', verbose_name='Успеваемость студента')),
            ],
            options={
                'verbose_name': 'Лог успеваемости студента',
                'verbose_name_plural': 'Логи успеваемости студентов',
            },
        ),
    ]
