# Generated by Django 2.2.4 on 2019-12-09 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0020_auto_20191209_1010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JournalStatus',
        ),
    ]
