# Generated by Django 2.2.4 on 2019-12-12 09:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0045_auto_20191211_1526'),
        ('schedules', '0022_auto_20191211_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTeacher',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Lesson', verbose_name='Занятие')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Препод-Занятие',
                'verbose_name_plural': 'Препод-Занятие',
                'unique_together': {('lesson', 'teacher')},
            },
        ),
    ]
