# Generated by Django 2.2.4 on 2019-12-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0045_auto_20191211_1526'),
        ('schedules', '0024_lessonstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicjournal',
            name='teachers',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='groups',
        ),
        migrations.AddField(
            model_name='lesson',
            name='load_type2_uid_1c',
            field=models.CharField(default='', max_length=200, verbose_name='УИД 1С Типа нагрузки'),
        ),
        migrations.AddField(
            model_name='lessonteacher',
            name='flow_uid',
            field=models.UUIDField(null=True, verbose_name='UID потока'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonteacher',
            unique_together={('flow_uid', 'teacher')},
        ),
        migrations.RemoveField(
            model_name='lessonteacher',
            name='lesson',
        ),
    ]
