# Generated by Django 2.2.4 on 2019-12-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0025_auto_20191213_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradingsystem',
            name='name',
            field=models.CharField(max_length=800, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gradingsystem',
            name='name_en',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gradingsystem',
            name='name_kk',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='gradingsystem',
            name='name_ru',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lessonstatus',
            name='name',
            field=models.CharField(max_length=800, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lessonstatus',
            name='name_en',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lessonstatus',
            name='name_kk',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='lessonstatus',
            name='name_ru',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='name',
            field=models.CharField(max_length=800, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='name_en',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='name_kk',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='name_ru',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=800, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name_en',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name_kk',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name_ru',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=800, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name_en',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name_kk',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name_ru',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='timewindow',
            name='name',
            field=models.CharField(max_length=800, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='timewindow',
            name='name_en',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='timewindow',
            name='name_kk',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='timewindow',
            name='name_ru',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
    ]
