# Generated by Django 2.2.4 on 2019-12-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0029_lesson_admin_allow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='value_letter',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Оценка по буквенной системе'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='value_number',
            field=models.FloatField(blank=True, null=True, verbose_name='Цифровой эквивалент'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='value_traditional',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Оценка по традиционной системе'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='value_traditional_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Оценка по традиционной системе'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='value_traditional_kk',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Оценка по традиционной системе'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='value_traditional_ru',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Оценка по традиционной системе'),
        ),
    ]
