# Generated by Django 2.2.4 on 2019-12-26 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0077_studentdiscipline_uid_1c'),
        ('schedules', '0030_auto_20191224_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicjournal',
            name='study_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.StudyPeriod', verbose_name='Учебный год'),
        ),
    ]
