# Generated by Django 2.2.4 on 2019-12-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0031_electronicjournal_study_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='electronicjournal',
            name='block_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата блокировки'),
        ),
    ]
