# Generated by Django 2.2.4 on 2019-10-24 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0051_auto_20191022_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(3, 'Отклонено'), (4, 'Утверждено')])),
                ('comment', models.TextField()),
                ('acad_periods', models.ManyToManyField(to='organizations.AcadPeriod')),
                ('study_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.StudyPlan')),
            ],
            options={
                'verbose_name': 'Метка Эдвайзера',
                'verbose_name_plural': 'Метки Эдвайзера',
            },
        ),
    ]
