# Generated by Django 2.2.4 on 2019-10-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorcheck',
            name='comment',
            field=models.TextField(default=''),
        ),
    ]
