# Generated by Django 2.2.4 on 2019-10-24 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0002_auto_20191024_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisorcheck',
            name='comment',
            field=models.TextField(default='', null=True),
        ),
    ]
