# Generated by Django 2.2.4 on 2019-10-31 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0054_auto_20191030_0934'),
        ('advisors', '0004_auto_20191030_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisorcheck',
            name='acad_periods',
        ),
        migrations.AddField(
            model_name='advisorcheck',
            name='acad_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.AcadPeriod'),
        ),
    ]
