# Generated by Django 2.2.4 on 2020-03-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0007_auto_20200316_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themesoftheses',
            name='study_plan',
        ),
        migrations.AddField(
            model_name='themesoftheses',
            name='uid_1c',
            field=models.CharField(max_length=100, null=True, verbose_name='uid 1C'),
        ),
    ]
