# Generated by Django 2.2.4 on 2020-03-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0008_auto_20200317_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesoftheses',
            name='supervisor_leader',
            field=models.TextField(blank=True, null=True, verbose_name='Руководитель извне'),
        ),
    ]
