# Generated by Django 2.2.4 on 2020-04-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0011_auto_20200331_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesoftheses',
            name='code',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
