# Generated by Django 2.2.4 on 2020-04-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0012_themesoftheses_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesoftheses',
            name='uuid_1c',
            field=models.CharField(blank=True, default='', help_text='придет, после выгрузки в 1С', max_length=100, null=True, verbose_name='УИД документа-аналога в 1С'),
        ),
        migrations.AlterField(
            model_name='themesoftheses',
            name='uid_1c',
            field=models.CharField(max_length=100, null=True, verbose_name='uid 1C'),
        ),
    ]
