# Generated by Django 2.2.4 on 2020-06-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisors', '0013_auto_20200424_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesoftheses',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
