# Generated by Django 2.2.4 on 2020-03-10 07:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0097_remove_disciplinecredit_control_form'),
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLevel',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('name', models.CharField(max_length=800, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=800, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=800, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=800, null=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Budget level',
                'verbose_name_plural': 'Budget levels',
            },
        ),
        migrations.AlterModelOptions(
            name='addresstype',
            options={'verbose_name': 'Address type', 'verbose_name_plural': 'Address types'},
        ),
        migrations.AlterModelOptions(
            name='documentreturnmethod',
            options={'verbose_name': 'Document return method', 'verbose_name_plural': 'Document return methods'},
        ),
        migrations.AlterModelOptions(
            name='familymembership',
            options={'verbose_name': 'Family membership', 'verbose_name_plural': 'Family memberships'},
        ),
        migrations.AlterModelOptions(
            name='privilegetype',
            options={'verbose_name': 'Privilege type', 'verbose_name_plural': 'Privilege types'},
        ),
        migrations.RenameField(
            model_name='admissioncampaign',
            old_name='chosen_direction_max_count',
            new_name='chosen_directions_max_count',
        ),
        migrations.AlterField(
            model_name='campaignstage',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stages', to='applicant.AdmissionCampaign', verbose_name='Admission campaign'),
        ),
        migrations.AlterField(
            model_name='campaignstage',
            name='prep_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign_stages', to='organizations.PreparationLevel', verbose_name='Preparation level'),
        ),
        migrations.CreateModel(
            name='RecruitmentPlan',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('study_plan_1c', models.CharField(max_length=500, verbose_name='1C study plan')),
                ('admission_basis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.EducationBase', verbose_name='Admission basis')),
                ('based_on', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.EducationType', verbose_name='Based on')),
                ('budget_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.BudgetLevel', verbose_name='Budget level')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plans', to='applicant.AdmissionCampaign', verbose_name='Recruitment plan')),
                ('education_program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.EducationProgram', verbose_name='Education program')),
                ('education_program_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.EducationProgramGroup', verbose_name='Group of education programs')),
                ('entrance_test_form', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.ControlForm', verbose_name='Entrance test form')),
                ('graduating_cathedra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.Cathedra', verbose_name='Graduating cathedra')),
                ('prep_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plans', to='organizations.PreparationLevel', verbose_name='Preparation level')),
                ('study_form', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.StudyForm', verbose_name='Study Form')),
                ('study_period', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.StudyPeriod', verbose_name='Study period')),
                ('training_direction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.Speciality', verbose_name='Training direction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
