# Generated by Django 2.2.4 on 2020-03-19 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprivilegelist',
            name='questionnaire',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.Questionnaire', verbose_name='Questionnaire'),
        ),
    ]
