# Generated by Django 2.2.4 on 2020-03-20 10:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0056_merge_20200312_1209'),
        ('organizations', '0113_auto_20200320_1603'),
        ('applicant', '0002_auto_20200319_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
            ],
            options={
                'verbose_name': 'Заявление',
                'verbose_name_plural': 'Заявления',
            },
        ),
        migrations.CreateModel(
            name='DirectionChoice',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('education_base', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.EducationBase', verbose_name='Основание поступления')),
                ('education_language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.Language', verbose_name='Язык обучения')),
                ('education_program', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.EducationProgram', verbose_name='Образовательная программа')),
                ('education_program_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.EducationProgramGroup', verbose_name='Группа образовательных программ')),
                ('prep_level', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.PreparationLevel', verbose_name='Уровень образования')),
                ('study_form', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.StudyForm', verbose_name='Форма обучения')),
            ],
            options={
                'verbose_name': 'Выбор направления',
                'verbose_name_plural': 'Выборы направлений',
            },
        ),
        migrations.CreateModel(
            name='DisciplineMark',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('mark', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(40)])),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.Discipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Пройденная дисциплина на ЕНТ/КТ',
                'verbose_name_plural': 'Пройденные дисциплины на ЕНТ/КТ',
            },
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('issued_at', models.DateField(verbose_name='Дата выдачи')),
                ('serial_number', models.PositiveSmallIntegerField(verbose_name='Серийный номер')),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер')),
                ('date_of_order', models.DateField(verbose_name='Дата приказа МОН РК')),
                ('number_order', models.PositiveSmallIntegerField(verbose_name='Номер приказа МОН РК')),
                ('education_program_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.EducationProgramGroup', verbose_name='Группа образовательных программ')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='portal_users.Profile', verbose_name='Профиль')),
            ],
            options={
                'verbose_name': 'Грант',
                'verbose_name_plural': 'Грант',
            },
        ),
        migrations.CreateModel(
            name='GrantType',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('name', models.CharField(max_length=800, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид гранта',
                'verbose_name_plural': 'Виды грантов',
            },
        ),
        migrations.CreateModel(
            name='InternationalCert',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('mark', models.PositiveSmallIntegerField(verbose_name='Балл')),
                ('issued_at', models.DateField(verbose_name='Дата получения')),
                ('number', models.CharField(max_length=100, verbose_name='Номер сертификата')),
            ],
            options={
                'verbose_name': 'Международный сертификат',
                'verbose_name_plural': 'Международные сертификаты',
            },
        ),
        migrations.CreateModel(
            name='InternationalCertType',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('name', models.CharField(max_length=800, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип международного сертификата',
                'verbose_name_plural': 'Типы международных сертификатов',
            },
        ),
        migrations.CreateModel(
            name='LanguageProficiency',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('code', models.CharField(max_length=100, verbose_name='Код')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='applicant.LanguageProficiency')),
            ],
            options={
                'verbose_name': 'Уровень владения языком',
                'verbose_name_plural': 'Уровени владения языками',
            },
        ),
        migrations.CreateModel(
            name='TestCert',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('number', models.PositiveSmallIntegerField(verbose_name='Номер сертификата')),
                ('issued_at', models.DateField(verbose_name='Дата сдачи экзамена')),
                ('confirmation_document_provided', models.BooleanField(default=False, verbose_name='Подтверждающий документ предоставлен')),
                ('disciplines', models.ManyToManyField(to='applicant.DisciplineMark', verbose_name='Дисциплны')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.Language', verbose_name='Язык сдачи')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Профиль пользователя')),
            ],
            options={
                'verbose_name': 'Серитификат ЕНТ/КТ',
                'verbose_name_plural': 'Серитификаты ЕНТ/КТ',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('disciplines', models.ManyToManyField(to='applicant.DisciplineMark', verbose_name='Пройденные дисциплины')),
                ('test_certificate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.TestCert', verbose_name='Сертификат теста')),
            ],
            options={
                'verbose_name': 'Результат ЕНТ/КТ',
                'verbose_name_plural': 'Результаты ЕНТ/КТ',
            },
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='diploma_scan',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='education_base',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='ent_results',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='files',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='form',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='grant_scan',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='programs',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='status',
        ),
        migrations.DeleteModel(
            name='AdmissionCampaignType',
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Адрес', 'verbose_name_plural': 'Адреса'},
        ),
        migrations.AlterModelOptions(
            name='addressclassifier',
            options={'verbose_name': 'Адресный классификатор', 'verbose_name_plural': 'Адресные классификаторы'},
        ),
        migrations.AlterModelOptions(
            name='addresstype',
            options={'verbose_name': 'Тип адреса', 'verbose_name_plural': 'Типы адресов'},
        ),
        migrations.AlterModelOptions(
            name='admissioncampaign',
            options={'verbose_name': 'Приемная кампания', 'verbose_name_plural': 'Приемные кампании'},
        ),
        migrations.AlterModelOptions(
            name='applicant',
            options={'verbose_name': 'Абитуриент', 'verbose_name_plural': 'Абитуриенты'},
        ),
        migrations.AlterModelOptions(
            name='budgetlevel',
            options={'verbose_name': 'Уровень бюджета', 'verbose_name_plural': 'Уровни бюджета'},
        ),
        migrations.AlterModelOptions(
            name='campaignstage',
            options={'verbose_name': 'Этап кампании', 'verbose_name_plural': 'Этапы кампаний'},
        ),
        migrations.AlterModelOptions(
            name='documentreturnmethod',
            options={'verbose_name': 'Метод возврата документа', 'verbose_name_plural': 'Методы возврата документов'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Семья', 'verbose_name_plural': 'Семьи'},
        ),
        migrations.AlterModelOptions(
            name='familymember',
            options={'verbose_name': 'Член семьи', 'verbose_name_plural': 'Члены семьи'},
        ),
        migrations.AlterModelOptions(
            name='familymembership',
            options={'verbose_name': 'Степень родства', 'verbose_name_plural': 'Степени родства'},
        ),
        migrations.AlterModelOptions(
            name='privilege',
            options={'verbose_name': 'Льгота', 'verbose_name_plural': 'Льготы'},
        ),
        migrations.AlterModelOptions(
            name='privilegetype',
            options={'verbose_name': 'Тип льготы', 'verbose_name_plural': 'Типы льготы'},
        ),
        migrations.AlterModelOptions(
            name='questionnaire',
            options={'verbose_name': 'Анкета', 'verbose_name_plural': 'Анкеты'},
        ),
        migrations.AlterModelOptions(
            name='recruitmentplan',
            options={'verbose_name': 'План набора', 'verbose_name_plural': 'Планы наборов'},
        ),
        migrations.AlterModelOptions(
            name='userprivilegelist',
            options={'verbose_name': 'Список льгот пользователя', 'verbose_name_plural': 'Списки льгот пользователей'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='address',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='address',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='recruitmentplan',
            name='training_direction',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='creator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal_users.Profile', verbose_name='Подающий анкету'),
        ),
        migrations.AddField(
            model_name='recruitmentplan',
            name='prep_direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.Speciality', verbose_name='Направление подготовки'),
        ),
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Квартира'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cities', to='applicant.AddressClassifier', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='address',
            name='corpus',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses', to='common.Citizenship', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='districts', to='applicant.AddressClassifier', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='address',
            name='home_number',
            field=models.CharField(max_length=500, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='address',
            name='index',
            field=models.CharField(max_length=100, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='address',
            name='locality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='localities', to='applicant.AddressClassifier', verbose_name='Населенный пункт'),
        ),
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses', to='portal_users.Profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='regions', to='applicant.AddressClassifier', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=500, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.AddressType', verbose_name='Тип адреса'),
        ),
        migrations.AlterField(
            model_name='addressclassifier',
            name='address_element_type',
            field=models.PositiveSmallIntegerField(verbose_name='Тип адресного элемента'),
        ),
        migrations.AlterField(
            model_name='addressclassifier',
            name='code',
            field=models.PositiveSmallIntegerField(verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='addressclassifier',
            name='district_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Код района'),
        ),
        migrations.AlterField(
            model_name='addressclassifier',
            name='locality_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Код населенного пункта'),
        ),
        migrations.AlterField(
            model_name='addressclassifier',
            name='region_code',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Код региона'),
        ),
        migrations.AlterField(
            model_name='admissioncampaign',
            name='chosen_directions_max_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Максимальное кол-во выбранных направлений'),
        ),
        migrations.AlterField(
            model_name='admissioncampaign',
            name='education_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.EducationType', verbose_name='Тип образования'),
        ),
        migrations.AlterField(
            model_name='admissioncampaign',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания приемной кампании'),
        ),
        migrations.AlterField(
            model_name='admissioncampaign',
            name='inter_cert_foreign_lang',
            field=models.BooleanField(default=False, verbose_name='Международный сертификат по иностранному языку'),
        ),
        migrations.AlterField(
            model_name='admissioncampaign',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала приемной кампании'),
        ),
        migrations.AlterField(
            model_name='admissioncampaign',
            name='use_contest_groups',
            field=models.BooleanField(default=False, verbose_name='Использовать конкурсные группы'),
        ),
        migrations.AlterField(
            model_name='admissioncampaign',
            name='year',
            field=models.CharField(max_length=4, verbose_name='Год поступления'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='consented',
            field=models.BooleanField(default=False, verbose_name='Даю согласие на обработку моих персональных данных'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='doc_num',
            field=models.CharField(max_length=16, unique=True, verbose_name='Серийный номер документа'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='order_number',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='prep_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.PreparationLevel', verbose_name='Уровень подготовки'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applicant', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='applicationstatus',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Код статуса'),
        ),
        migrations.AlterField(
            model_name='campaignstage',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='stages', to='applicant.AdmissionCampaign', verbose_name='Приемная кампания'),
        ),
        migrations.AlterField(
            model_name='campaignstage',
            name='education_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.EducationBase', verbose_name='Основа поступления'),
        ),
        migrations.AlterField(
            model_name='campaignstage',
            name='end_date',
            field=models.DateTimeField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='campaignstage',
            name='prep_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='campaign_stages', to='organizations.PreparationLevel', verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='campaignstage',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='campaignstage',
            name='study_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.StudyForm', verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='docscan',
            name='content_type',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='docscan',
            name='ext',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Расширение файла'),
        ),
        migrations.AlterField(
            model_name='docscan',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='docscan',
            name='path',
            field=models.TextField(blank=True, null=True, verbose_name='Путь к файлу'),
        ),
        migrations.AlterField(
            model_name='docscan',
            name='size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Размер файла'),
        ),
        migrations.AlterField(
            model_name='family',
            name='number_of_children',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во детей в семье'),
        ),
        migrations.AlterField(
            model_name='family',
            name='number_of_young_children',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во несовершеннолетних детей в семье'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.Address', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='email',
            field=models.EmailField(max_length=500, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='family',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='applicant.Family', verbose_name='Семья'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='first_name',
            field=models.CharField(default='', max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='last_name',
            field=models.CharField(default='', max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.FamilyMembership', verbose_name='Степень родства'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='phone',
            field=models.CharField(max_length=500, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='position',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='portal_users.Profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='workplace',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='doc_number',
            field=models.CharField(max_length=100, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='doc_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.DocumentType', verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='end_date',
            field=models.DateField(verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='issued_at',
            field=models.DateField(verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='issued_by',
            field=models.CharField(max_length=200, verbose_name='Кем выдано'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='privileges', to='applicant.UserPrivilegeList', verbose_name='Список льгот'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.DocScan', verbose_name='Скан документа'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='serial_number',
            field=models.CharField(max_length=100, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.PrivilegeType', verbose_name='Тип льготы'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='address_of_registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='registration_addresses', to='applicant.Address', verbose_name='Адрес по прописке'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='address_of_residence',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='residence_addresses', to='applicant.Address', verbose_name='Адрес проживания'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='address_of_temp_reg',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='temporary_addresses', to='applicant.Address', verbose_name='Адрес временной регистрации'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='birthday',
            field=models.DateField(verbose_name='День рождения'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='birthplace',
            field=models.CharField(max_length=500, verbose_name='Место рождения'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='citizenship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.Citizenship', verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='experience_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)], verbose_name='Опыт в месяцах'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Опыт в годах'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='family',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='questionnaires', to='applicant.Family', verbose_name='Семья'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='first_name_en',
            field=models.CharField(max_length=255, verbose_name='Имя на латинице'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal_users.Gender', verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='id_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.IdentityDocument', verbose_name='Удо'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='id_doc_scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='application_id_doc', to='applicant.DocScan', verbose_name='Удо скан'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='iin',
            field=models.CharField(max_length=100, verbose_name='ИИН'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='last_name_en',
            field=models.CharField(max_length=255, verbose_name='Фамилия на латинице'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='marital_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal_users.MaritalStatus', verbose_name='Семейное положение'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.Nationality', verbose_name='Национальность'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='phone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='phones', to='portal_users.ProfilePhone', verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='position',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='workplace',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Место работы'),
        ),
        migrations.AlterField(
            model_name='recruitmentplan',
            name='admission_basis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.EducationBase', verbose_name='Основание для посутпления'),
        ),
        migrations.AlterField(
            model_name='recruitmentplan',
            name='based_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.EducationType', verbose_name='На базе'),
        ),
        migrations.AlterField(
            model_name='recruitmentplan',
            name='budget_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.BudgetLevel', verbose_name='Уровень бюджета'),
        ),
        migrations.AlterField(
            model_name='recruitmentplan',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plans', to='applicant.AdmissionCampaign', verbose_name='План набора'),
        ),
        migrations.AlterField(
            model_name='recruitmentplan',
            name='education_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.EducationProgram', verbose_name='Образовательная программа'),
        ),
        migrations.AlterField(
            model_name='recruitmentplan',
            name='education_program_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.EducationProgramGroup', verbose_name='Группа образовательных программ'),
        ),
        migrations.AlterField(
            model_name='recruitmentplan',
            name='entrance_test_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.ControlForm', verbose_name='Форма вступительного испытания'),
        ),
        migrations.AlterField(
            model_name='recruitmentplan',
            name='graduating_cathedra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.Cathedra', verbose_name='Выпускающая кафедра'),
        ),
        migrations.AlterField(
            model_name='recruitmentplan',
            name='prep_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='plans', to='organizations.PreparationLevel', verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='recruitmentplan',
            name='study_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.StudyForm', verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='recruitmentplan',
            name='study_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.StudyPeriod', verbose_name='Учебный период'),
        ),
        migrations.AlterField(
            model_name='recruitmentplan',
            name='study_plan_1c',
            field=models.CharField(max_length=500, verbose_name='Учебный план из 1С'),
        ),
        migrations.AlterField(
            model_name='userprivilegelist',
            name='doc_return_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.DocumentReturnMethod', verbose_name='Метод возврата документов'),
        ),
        migrations.AlterField(
            model_name='userprivilegelist',
            name='need_dormitory',
            field=models.BooleanField(default=False, verbose_name='Нуждаюсь в общежитии'),
        ),
        migrations.AlterField(
            model_name='userprivilegelist',
            name='questionnaire',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.Questionnaire', verbose_name='Анкета'),
        ),
        migrations.DeleteModel(
            name='AdmissionApplication',
        ),
        migrations.AddField(
            model_name='testcert',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.DocScan', verbose_name='Скан сертификата'),
        ),
        migrations.AddField(
            model_name='internationalcert',
            name='language_proficiency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.LanguageProficiency', verbose_name='Владение языком (CERF)'),
        ),
        migrations.AddField(
            model_name='internationalcert',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Профиль'),
        ),
        migrations.AddField(
            model_name='internationalcert',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.InternationalCertType', verbose_name='Тип международного сертификата'),
        ),
        migrations.AddField(
            model_name='grant',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.DocScan', verbose_name='Скан'),
        ),
        migrations.AddField(
            model_name='grant',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.GrantType', verbose_name='Вид гранта'),
        ),
        migrations.AddField(
            model_name='application',
            name='discipline_choices',
            field=models.ManyToManyField(to='applicant.DirectionChoice', verbose_name='Выборы направлений'),
        ),
        migrations.AddField(
            model_name='application',
            name='grant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.Grant', verbose_name='Грант'),
        ),
        migrations.AddField(
            model_name='application',
            name='international_cert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.InternationalCert', verbose_name='Международный сертификат'),
        ),
        migrations.AddField(
            model_name='application',
            name='previous_education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organizations.Education', verbose_name='Предыдущее образование'),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.ApplicationStatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='application',
            name='test_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.TestResult', verbose_name='Результат теста ЕНТ/КТ'),
        ),
    ]
