# Generated by Django 2.2.4 on 2020-03-11 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_auto_20200310_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='verified',
        ),
    ]
