# Generated by Django 2.2.4 on 2020-03-20 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_auto_20200320_1603'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationstatus',
            options={'verbose_name': 'Статус заявления', 'verbose_name_plural': 'Статусы заявлений'},
        ),
        migrations.AlterModelOptions(
            name='docscan',
            options={'verbose_name': 'Скан документа', 'verbose_name_plural': 'Сканы документов'},
        ),
    ]
