# Generated by Django 2.2.4 on 2020-03-20 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0056_merge_20200312_1209'),
        ('applicant', '0004_auto_20200320_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='creator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Заявитель'),
        ),
    ]
