# Generated by Django 2.2.4 on 2020-03-26 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0114_education_scan'),
        ('applicant', '0006_remove_testcert_disciplines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='education_program_group',
        ),
        migrations.AddField(
            model_name='grant',
            name='speciality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Speciality', verbose_name='Группа образовательных программ'),
        ),
    ]
