# Generated by Django 2.2.4 on 2020-03-26 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0007_auto_20200326_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='discipline_choices',
            new_name='directions',
        ),
    ]
