# Generated by Django 2.2.4 on 2020-04-02 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_auto_20200326_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='iin',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
