# Generated by Django 2.2.4 on 2020-04-03 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0010_auto_20200403_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='portal_users.Profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='internationalcert',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Профиль'),
        ),
        migrations.AlterField(
            model_name='languageproficiency',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='children', to='applicant.LanguageProficiency'),
        ),
        migrations.AlterField(
            model_name='testcert',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Профиль пользователя'),
        ),
    ]
