# Generated by Django 2.2.4 on 2020-04-07 10:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0058_auto_20200403_1152'),
        ('applicant', '0012_auto_20200406_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.AdmissionCampaign', verbose_name='Кампания')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_users.Profile', verbose_name='Профиль')),
                ('files', models.ManyToManyField(to='applicant.DocScan', verbose_name='Сканы документов')),
                ('recruitment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.RecruitmentPlan', verbose_name='План набора')),
            ],
            options={
                'verbose_name': 'Перечень документов для приема на обучение',
                'verbose_name_plural': 'Перечни документов для приема на обучение',
            },
        ),
    ]
