# Generated by Django 2.2.4 on 2020-04-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0013_admissiondocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='granttype',
            name='name_en',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='granttype',
            name='name_kk',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='granttype',
            name='name_ru',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='internationalcerttype',
            name='name_en',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='internationalcerttype',
            name='name_kk',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='internationalcerttype',
            name='name_ru',
            field=models.CharField(max_length=800, null=True, verbose_name='Название'),
        ),
    ]
