# Generated by Django 2.2.4 on 2020-04-08 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0058_auto_20200403_1152'),
        ('applicant', '0014_auto_20200407_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionchoice',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directions', to='portal_users.Profile'),
        ),
        migrations.AddField(
            model_name='disciplinemark',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_disciplines', to='portal_users.Profile'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_users.Profile'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='applicant', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='testcert',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_test_certs', to='portal_users.Profile', verbose_name='Профиль пользователя'),
        ),
    ]
