# Generated by Django 2.2.4 on 2020-04-09 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0015_auto_20200408_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='questionnaire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='number',
            field=models.CharField(max_length=200, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='number_order',
            field=models.CharField(max_length=200, verbose_name='Номер приказа МОН РК'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='serial_number',
            field=models.CharField(max_length=200, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='internationalcert',
            name='mark',
            field=models.FloatField(verbose_name='Балл'),
        ),
        migrations.AlterField(
            model_name='testcert',
            name='number',
            field=models.CharField(max_length=200, verbose_name='Номер сертификата'),
        ),
    ]
