# Generated by Django 2.2.4 on 2020-04-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0016_auto_20200409_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name_en',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='address',
            name='name_kk',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='address',
            name='name_ru',
            field=models.CharField(blank=True, max_length=800, null=True, verbose_name='Имя'),
        ),
    ]
