# Generated by Django 2.2.4 on 2020-04-11 13:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0017_auto_20200410_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('related_model_name', models.CharField(max_length=300, verbose_name='Название модели, которая была изменена')),
                ('key', models.CharField(max_length=300, verbose_name='Ключ')),
                ('old_value', models.CharField(blank=True, default='', max_length=300, verbose_name='Старое значение')),
                ('new_value', models.CharField(blank=True, default='', max_length=300, verbose_name='Новое значение')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelog', to='applicant.Application')),
            ],
            options={
                'verbose_name': 'Изменения заявления',
                'verbose_name_plural': 'Изменения заявлений',
            },
        ),
    ]
