# Generated by Django 2.2.4 on 2020-04-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0018_changelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressclassifier',
            name='address_element_type',
            field=models.PositiveIntegerField(verbose_name='Тип адресного элемента'),
        ),
        migrations.AlterField(
            model_name='addressclassifier',
            name='code',
            field=models.PositiveIntegerField(verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='addressclassifier',
            name='district_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Код района'),
        ),
        migrations.AlterField(
            model_name='addressclassifier',
            name='locality_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Код населенного пункта'),
        ),
        migrations.AlterField(
            model_name='addressclassifier',
            name='region_code',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Код региона'),
        ),
    ]
