# Generated by Django 2.2.4 on 2020-04-20 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0019_auto_20200417_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprivilegelist',
            name='doc_return_method',
        ),
        migrations.RemoveField(
            model_name='userprivilegelist',
            name='need_dormitory',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='doc_return_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='applicant.DocumentReturnMethod', verbose_name='Метод возврата документов'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='need_dormitory',
            field=models.BooleanField(default=False, verbose_name='Нуждаюсь в общежитии'),
        ),
    ]
