# Generated by Django 2.2.4 on 2020-04-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0021_auto_20200420_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='applications', to='applicant.DocScan', verbose_name='Файлы для поступления'),
        ),
    ]
