# Generated by Django 2.2.4 on 2020-04-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0022_application_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Changelog',
        ),
    ]
