# Generated by Django 2.2.4 on 2020-04-22 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0119_disciplinecredit_teacher'),
        ('applicant', '0023_delete_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentplan',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Language', verbose_name='Язык обучения'),
        ),
    ]
