# Generated by Django 2.2.4 on 2020-04-26 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0024_recruitmentplan_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissiondocument',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='application',
            name='files',
        ),
        migrations.AddField(
            model_name='application',
            name='admission_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.AdmissionDocument'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='addresses', to='common.Citizenship', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='address',
            name='home_number',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='address',
            name='index',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Улица'),
        ),
    ]
