# Generated by Django 2.2.4 on 2020-04-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0026_auto_20200427_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
    ]
