# Generated by Django 2.2.4 on 2020-05-04 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0031_questionnaire_is_experienced'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_matches',
            field=models.CharField(blank=True, choices=[(0, 'registration'), (1, 'temporary registration'), (2, 'residence'), (3, 'does not match')], max_length=1, null=True, verbose_name='Адрес соответствует'),
        ),
        migrations.AlterField(
            model_name='address',
            name='type',
            field=models.CharField(blank=True, choices=[(0, 'address of registration'), (1, 'address of temporary registration'), (2, 'address of residence')], max_length=1, null=True, verbose_name='Тип адреса'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='common.Nationality', verbose_name='Национальн()ость'),
        ),
        migrations.DeleteModel(
            name='AddressType',
        ),
    ]
