# Generated by Django 2.2.4 on 2020-05-05 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0063_auto_20200427_1240'),
        ('applicant', '0032_auto_20200505_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_matches',
        ),
        migrations.RemoveField(
            model_name='address',
            name='profile',
        ),
        migrations.AddField(
            model_name='address',
            name='profiles',
            field=models.ManyToManyField(blank=True, related_name='addresses', to='portal_users.Profile', verbose_name='Профили'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='address_matches',
            field=models.CharField(blank=True, choices=[(0, 'registration'), (1, 'temporary registration'), (2, 'residence'), (3, 'does not match')], max_length=1, null=True, verbose_name='Адрес соответствует'),
        ),
        migrations.AlterField(
            model_name='userprivilegelist',
            name='questionnaire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='privilege_list', to='applicant.Questionnaire', verbose_name='Анкета'),
        ),
    ]
