# Generated by Django 2.2.4 on 2020-05-08 09:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0036_auto_20200507_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedDirection',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('order_number', models.PositiveSmallIntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.RecruitmentPlan', verbose_name='План набора')),
            ],
            options={
                'verbose_name': 'Упорядоченный план набора',
                'verbose_name_plural': 'Упорядоченные планы наборов',
                'ordering': ['order_number'],
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='directions',
            field=models.ManyToManyField(to='applicant.OrderedDirection', verbose_name='Выборы направлений'),
        ),
    ]
