# Generated by Django 2.2.4 on 2020-05-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0037_auto_20200508_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_cert_holder',
            field=models.BooleanField(default=False, verbose_name='Обладатель международного языкового сертификата'),
        ),
    ]
