# Generated by Django 2.2.4 on 2020-05-19 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0038_application_is_cert_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressclassifier',
            name='code',
            field=models.PositiveIntegerField(verbose_name='Код'),
        ),
        migrations.AlterUniqueTogether(
            name='addressclassifier',
            unique_together={('address_element_type', 'code')},
        ),
    ]
