# Generated by Django 2.2.4 on 2020-05-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0039_auto_20200519_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='is_privileged',
            field=models.BooleanField(default=False, verbose_name='Имеет льготы'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='address_matches',
            field=models.CharField(blank=True, choices=[(0, 'Адресу регистрации/прописки'), (1, 'Адресу временной регистрации'), (3, 'Фактическому адресу')], max_length=1, null=True, verbose_name='Адрес соответствует'),
        ),
    ]
