# Generated by Django 2.2.4 on 2020-05-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0041_auto_20200521_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Город (текст)'),
        ),
    ]
