# Generated by Django 2.2.4 on 2020-05-25 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_auto_20200521_1750'),
        ('applicant', '0042_address_city_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='international_cert',
        ),
        migrations.AddField(
            model_name='application',
            name='international_certs',
            field=models.ManyToManyField(blank=True, to='applicant.InternationalCert', verbose_name='Международные сертификаты'),
        ),
        migrations.AddField(
            model_name='internationalcert',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Document', verbose_name='Документ'),
        ),
    ]
