# Generated by Django 2.2.4 on 2020-05-27 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0126_auto_20200526_0951'),
        ('applicant', '0043_auto_20200525_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='internationalcert',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.Language', verbose_name='Тест на здачу языка'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='doc_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='issued_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата получения'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='issued_by',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Кем выдано'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Серийный номер'),
        ),
    ]
