# Generated by Django 2.2.4 on 2020-05-28 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_users', '0065_auto_20200521_1554'),
        ('applicant', '0044_auto_20200527_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='profiles',
        ),
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='portal_users.Profile', verbose_name='Профиль'),
        ),
    ]
