# Generated by Django 2.2.4 on 2020-05-29 04:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_auto_20200521_1750'),
        ('applicant', '0045_auto_20200528_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentplan',
            name='entrance_test_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.ControlForm', verbose_name='Форма вступительного испытания'),
        ),
        migrations.CreateModel(
            name='Document1C',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный идентификатор')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('sort', models.IntegerField(default=500)),
                ('name', models.CharField(max_length=800, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=800, null=True, verbose_name='Название')),
                ('name_kk', models.CharField(max_length=800, null=True, verbose_name='Название')),
                ('name_en', models.CharField(max_length=800, null=True, verbose_name='Название')),
                ('code', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applicant.AdmissionCampaign', verbose_name='Приемная кампания')),
                ('types', models.ManyToManyField(to='common.DocumentType', verbose_name='Типы документов')),
            ],
            options={
                'verbose_name': 'Документ из 1С',
                'verbose_name_plural': 'Документы из 1С',
            },
        ),
        migrations.AddField(
            model_name='admissiondocument',
            name='document_1c',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document', to='applicant.Document1C'),
        ),
    ]
