# Generated by Django 2.2.4 on 2020-06-01 04:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('applicant', '0046_auto_20200529_1051'),
        ('applicant', '0044_applicationstatuschangehistory'),
    ]

    operations = [
    ]
