# Generated by Django 2.2.4 on 2020-06-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_auto_20200611_1722'),
        ('applicant', '0051_auto_20200611_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document1c',
            name='types',
        ),
        migrations.AddField(
            model_name='document1c',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents1c', to='common.DocumentType', verbose_name='Тип документа'),
        ),
    ]
