# Generated by Django 2.2.4 on 2020-06-12 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0052_auto_20200611_1740'),
        ('applicant', '0051_auto_20200610_1023'),
    ]

    operations = [
    ]
