# Generated by Django 2.2.4 on 2020-06-17 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0053_merge_20200612_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='unpassed_test',
            field=models.BooleanField(default=False, verbose_name='Не прошел ЕНТ или КТ'),
        ),
        migrations.AlterField(
            model_name='application',
            name='test_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='applicant.TestResult', verbose_name='Результат теста ЕНТ/КТ'),
        ),
    ]
