# Generated by Django 2.2.4 on 2020-06-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('applicant', '0056_auto_20200619_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status_action',
            field=models.BooleanField(default=False, verbose_name='Статус действия модератором'),
        ),
    ]
