# Generated by Django 2.2.4 on 2020-06-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0056_auto_20200619_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='is_orphan',
            field=models.BooleanField(default=False, verbose_name='Является сиротой'),
        ),
    ]
