# Generated by Django 2.2.4 on 2020-06-25 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0057_auto_20200625_1154'),
        ('applicant', '0057_application_status_action'),
    ]

    operations = [
    ]
