# Generated by Django 2.2.4 on 2020-07-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_institutionconfig'),
        ('applicant', '0059_auto_20200630_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissiondocument',
            name='files',
            field=models.ManyToManyField(blank=True, to='common.File', verbose_name='Сканы'),
        ),
        migrations.AddField(
            model_name='grant',
            name='files',
            field=models.ManyToManyField(blank=True, to='common.File', verbose_name='Сканы'),
        ),
        migrations.AddField(
            model_name='internationalcert',
            name='files',
            field=models.ManyToManyField(blank=True, to='common.File', verbose_name='Сканы'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='files',
            field=models.ManyToManyField(blank=True, to='common.File', verbose_name='Сканы'),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='files',
            field=models.ManyToManyField(blank=True, to='common.File', verbose_name='Сканы'),
        ),
        migrations.AddField(
            model_name='testcert',
            name='files',
            field=models.ManyToManyField(blank=True, to='common.File', verbose_name='Сканы'),
        ),
    ]
