# Generated by Django 2.2.4 on 2020-07-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_institutionconfig'),
        ('applicant', '0059_auto_20200630_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissiondocument',
            name='document',
        ),
        migrations.AddField(
            model_name='admissiondocument',
            name='document',
            field=models.ManyToManyField(blank=True, to='common.File', verbose_name='Сканы документов'),
        ),
        migrations.RemoveField(
            model_name='grant',
            name='document',
        ),
        migrations.AddField(
            model_name='grant',
            name='document',
            field=models.ManyToManyField(to='common.File', verbose_name='Сканы'),
        ),
        migrations.RemoveField(
            model_name='internationalcert',
            name='document',
        ),
        migrations.AddField(
            model_name='internationalcert',
            name='document',
            field=models.ManyToManyField(to='common.File', verbose_name='Сканы документа'),
        ),
        migrations.RemoveField(
            model_name='privilege',
            name='document',
        ),
        migrations.AddField(
            model_name='privilege',
            name='document',
            field=models.ManyToManyField(to='common.File', verbose_name='Скан документа'),
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='id_document',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='id_document',
            field=models.ManyToManyField(to='common.File', verbose_name='Сканы удо'),
        ),
        migrations.RemoveField(
            model_name='testcert',
            name='document',
        ),
        migrations.AddField(
            model_name='testcert',
            name='document',
            field=models.ManyToManyField(to='common.File', verbose_name='Сканы сертификата'),
        ),
    ]
