# Generated by Django 2.2.4 on 2020-07-13 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0060_auto_20200710_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Document', verbose_name='Скан'),
        ),
        migrations.AlterField(
            model_name='internationalcert',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Document', verbose_name='Документ'),
        ),
        migrations.AlterField(
            model_name='privilege',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Document', verbose_name='Скан документа'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='id_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_id_doc', to='common.Document', verbose_name='Удо скан'),
        ),
        migrations.AlterField(
            model_name='testcert',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='common.Document', verbose_name='Скан сертификата'),
        ),
    ]
