# Generated by Django 2.2.4 on 2020-07-20 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0064_auto_20200717_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaire',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='phone2',
        ),
    ]
