# Generated by Django 2.2.4 on 2020-07-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0065_auto_20200720_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='uid_1c',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='UID документа в 1С'),
        ),
        migrations.AddField(
            model_name='application',
            name='uid_1c',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='UID документа в 1С'),
        ),
        migrations.AddField(
            model_name='grant',
            name='uid_1c',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='UID документа в 1С'),
        ),
        migrations.AddField(
            model_name='internationalcert',
            name='uid_1c',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='UID документа в 1С'),
        ),
        migrations.AddField(
            model_name='privilege',
            name='uid_1c',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='UID документа в 1С'),
        ),
        migrations.AddField(
            model_name='recruitmentplan',
            name='contest_group_uid',
            field=models.TextField(blank=True, null=True, verbose_name='UID конкурсной группы'),
        ),
        migrations.AddField(
            model_name='testcert',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Серия сетрификата'),
        ),
        migrations.AddField(
            model_name='testcert',
            name='test_date',
            field=models.DateField(null=True, verbose_name='День сдачи тестирования'),
        ),
        migrations.AddField(
            model_name='testcert',
            name='uid_1c',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='UID документа в 1С'),
        ),
    ]
