# Generated by Django 2.2.4 on 2020-07-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0066_auto_20200722_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='apply_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата подачи заявления'),
        ),
    ]
