# Generated by Django 2.2.4 on 2020-07-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0067_application_apply_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='modified_for_1c',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='applicant',
            name='modified_for_1c',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='application',
            name='modified_for_1c',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='disciplinemark',
            name='modified_for_1c',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='family',
            name='modified_for_1c',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='familymember',
            name='modified_for_1c',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='grant',
            name='modified_for_1c',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='internationalcert',
            name='modified_for_1c',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='privilege',
            name='modified_for_1c',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='modified_for_1c',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='testcert',
            name='modified_for_1c',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
